// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C {
  C() {}
  int f0() { return 0; }
  int f1() { return 1; }
  int f2() { return 2; }
  int f3() { return 3; }
  int f4() { return 4; }
  int f5() { return 5; }
  int f6() { return 6; }
  int f7() { return 7; }
  int f8() { return 8; }
  int f9() { return 9; }
  int f10() { return 10; }
  int f11() { return 11; }
  int f12() { return 12; }
  int f13() { return 13; }
  int f14() { return 14; }
  int f15() { return 15; }
  int f16() { return 16; }
  int f17() { return 17; }
  int f18() { return 18; }
  int f19() { return 19; }
  int f20() { return 20; }
  int f21() { return 21; }
  int f22() { return 22; }
  int f23() { return 23; }
  int f24() { return 24; }
  int f25() { return 25; }
  int f26() { return 26; }
  int f27() { return 27; }
  int f28() { return 28; }
  int f29() { return 29; }
  int f30() { return 30; }
  int f31() { return 31; }
  int f32() { return 32; }
  int f33() { return 33; }
  int f34() { return 34; }
  int f35() { return 35; }
  int f36() { return 36; }
  int f37() { return 37; }
  int f38() { return 38; }
  int f39() { return 39; }
  int f40() { return 40; }
  int f41() { return 41; }
  int f42() { return 42; }
  int f43() { return 43; }
  int f44() { return 44; }
  int f45() { return 45; }
  int f46() { return 46; }
  int f47() { return 47; }
  int f48() { return 48; }
  int f49() { return 49; }
  int f50() { return 50; }
  int f51() { return 51; }
  int f52() { return 52; }
  int f53() { return 53; }
  int f54() { return 54; }
  int f55() { return 55; }
  int f56() { return 56; }
  int f57() { return 57; }
  int f58() { return 58; }
  int f59() { return 59; }
  int f60() { return 60; }
  int f61() { return 61; }
  int f62() { return 62; }
  int f63() { return 63; }
  int f64() { return 64; }
  int f65() { return 65; }
  int f66() { return 66; }
  int f67() { return 67; }
  int f68() { return 68; }
  int f69() { return 69; }
  int f70() { return 70; }
  int f71() { return 71; }
  int f72() { return 72; }
  int f73() { return 73; }
  int f74() { return 74; }
  int f75() { return 75; }
  int f76() { return 76; }
  int f77() { return 77; }
  int f78() { return 78; }
  int f79() { return 79; }
  int f80() { return 80; }
  int f81() { return 81; }
  int f82() { return 82; }
  int f83() { return 83; }
  int f84() { return 84; }
  int f85() { return 85; }
  int f86() { return 86; }
  int f87() { return 87; }
  int f88() { return 88; }
  int f89() { return 89; }
  int f90() { return 90; }
  int f91() { return 91; }
  int f92() { return 92; }
  int f93() { return 93; }
  int f94() { return 94; }
  int f95() { return 95; }
  int f96() { return 96; }
  int f97() { return 97; }
  int f98() { return 98; }
  int f99() { return 99; }

}

void test() {
	C c = new C();
	assert(c.f0() == 0);
	assert(c.f1() == 1);
	assert(c.f2() == 2);
	assert(c.f3() == 3);
	assert(c.f4() == 4);
	assert(c.f5() == 5);
	assert(c.f6() == 6);
	assert(c.f7() == 7);
	assert(c.f8() == 8);
	assert(c.f9() == 9);
	assert(c.f10() == 10);
	assert(c.f11() == 11);
	assert(c.f12() == 12);
	assert(c.f13() == 13);
	assert(c.f14() == 14);
	assert(c.f15() == 15);
	assert(c.f16() == 16);
	assert(c.f17() == 17);
	assert(c.f18() == 18);
	assert(c.f19() == 19);
	assert(c.f20() == 20);
	assert(c.f21() == 21);
	assert(c.f22() == 22);
	assert(c.f23() == 23);
	assert(c.f24() == 24);
	assert(c.f25() == 25);
	assert(c.f26() == 26);
	assert(c.f27() == 27);
	assert(c.f28() == 28);
	assert(c.f29() == 29);
	assert(c.f30() == 30);
	assert(c.f31() == 31);
	assert(c.f32() == 32);
	assert(c.f33() == 33);
	assert(c.f34() == 34);
	assert(c.f35() == 35);
	assert(c.f36() == 36);
	assert(c.f37() == 37);
	assert(c.f38() == 38);
	assert(c.f39() == 39);
	assert(c.f40() == 40);
	assert(c.f41() == 41);
	assert(c.f42() == 42);
	assert(c.f43() == 43);
	assert(c.f44() == 44);
	assert(c.f45() == 45);
	assert(c.f46() == 46);
	assert(c.f47() == 47);
	assert(c.f48() == 48);
	assert(c.f49() == 49);
	assert(c.f50() == 50);
	assert(c.f51() == 51);
	assert(c.f52() == 52);
	assert(c.f53() == 53);
	assert(c.f54() == 54);
	assert(c.f55() == 55);
	assert(c.f56() == 56);
	assert(c.f57() == 57);
	assert(c.f58() == 58);
	assert(c.f59() == 59);
	assert(c.f60() == 60);
	assert(c.f61() == 61);
	assert(c.f62() == 62);
	assert(c.f63() == 63);
	assert(c.f64() == 64);
	assert(c.f65() == 65);
	assert(c.f66() == 66);
	assert(c.f67() == 67);
	assert(c.f68() == 68);
	assert(c.f69() == 69);
	assert(c.f70() == 70);
	assert(c.f71() == 71);
	assert(c.f72() == 72);
	assert(c.f73() == 73);
	assert(c.f74() == 74);
	assert(c.f75() == 75);
	assert(c.f76() == 76);
	assert(c.f77() == 77);
	assert(c.f78() == 78);
	assert(c.f79() == 79);
	assert(c.f80() == 80);
	assert(c.f81() == 81);
	assert(c.f82() == 82);
	assert(c.f83() == 83);
	assert(c.f84() == 84);
	assert(c.f85() == 85);
	assert(c.f86() == 86);
	assert(c.f87() == 87);
	assert(c.f88() == 88);
	assert(c.f89() == 89);
	assert(c.f90() == 90);
	assert(c.f91() == 91);
	assert(c.f92() == 92);
	assert(c.f93() == 93);
	assert(c.f94() == 94);
	assert(c.f95() == 95);
	assert(c.f96() == 96);
	assert(c.f97() == 97);
	assert(c.f98() == 98);
	assert(c.f99() == 99);

}

test();
