// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C {
  C() {}
  int f0() { return 0; }
  int f1() { return 1; }
  int f2() { return 2; }
  int f3() { return 3; }
  int f4() { return 4; }
  int f5() { return 5; }
  int f6() { return 6; }
  int f7() { return 7; }
  int f8() { return 8; }
  int f9() { return 9; }
  int f10() { return 10; }
  int f11() { return 11; }
  int f12() { return 12; }
  int f13() { return 13; }
  int f14() { return 14; }
  int f15() { return 15; }
  int f16() { return 16; }
  int f17() { return 17; }
  int f18() { return 18; }
  int f19() { return 19; }
  int f20() { return 20; }
  int f21() { return 21; }
  int f22() { return 22; }
  int f23() { return 23; }
  int f24() { return 24; }
  int f25() { return 25; }
  int f26() { return 26; }
  int f27() { return 27; }
  int f28() { return 28; }
  int f29() { return 29; }
  int f30() { return 30; }
  int f31() { return 31; }
  int f32() { return 32; }
  int f33() { return 33; }
  int f34() { return 34; }
  int f35() { return 35; }
  int f36() { return 36; }
  int f37() { return 37; }
  int f38() { return 38; }
  int f39() { return 39; }
  int f40() { return 40; }
  int f41() { return 41; }
  int f42() { return 42; }
  int f43() { return 43; }
  int f44() { return 44; }
  int f45() { return 45; }
  int f46() { return 46; }
  int f47() { return 47; }
  int f48() { return 48; }
  int f49() { return 49; }
  int f50() { return 50; }
  int f51() { return 51; }
  int f52() { return 52; }
  int f53() { return 53; }
  int f54() { return 54; }
  int f55() { return 55; }
  int f56() { return 56; }
  int f57() { return 57; }
  int f58() { return 58; }
  int f59() { return 59; }
  int f60() { return 60; }
  int f61() { return 61; }
  int f62() { return 62; }
  int f63() { return 63; }
  int f64() { return 64; }
  int f65() { return 65; }
  int f66() { return 66; }
  int f67() { return 67; }
  int f68() { return 68; }
  int f69() { return 69; }
  int f70() { return 70; }
  int f71() { return 71; }
  int f72() { return 72; }
  int f73() { return 73; }
  int f74() { return 74; }
  int f75() { return 75; }
  int f76() { return 76; }
  int f77() { return 77; }
  int f78() { return 78; }
  int f79() { return 79; }
  int f80() { return 80; }
  int f81() { return 81; }
  int f82() { return 82; }
  int f83() { return 83; }
  int f84() { return 84; }
  int f85() { return 85; }
  int f86() { return 86; }
  int f87() { return 87; }
  int f88() { return 88; }
  int f89() { return 89; }
  int f90() { return 90; }
  int f91() { return 91; }
  int f92() { return 92; }
  int f93() { return 93; }
  int f94() { return 94; }
  int f95() { return 95; }
  int f96() { return 96; }
  int f97() { return 97; }
  int f98() { return 98; }
  int f99() { return 99; }
  int f100() { return 100; }
  int f101() { return 101; }
  int f102() { return 102; }
  int f103() { return 103; }
  int f104() { return 104; }
  int f105() { return 105; }
  int f106() { return 106; }
  int f107() { return 107; }
  int f108() { return 108; }
  int f109() { return 109; }
  int f110() { return 110; }
  int f111() { return 111; }
  int f112() { return 112; }
  int f113() { return 113; }
  int f114() { return 114; }
  int f115() { return 115; }
  int f116() { return 116; }
  int f117() { return 117; }
  int f118() { return 118; }
  int f119() { return 119; }
  int f120() { return 120; }
  int f121() { return 121; }
  int f122() { return 122; }
  int f123() { return 123; }
  int f124() { return 124; }
  int f125() { return 125; }
  int f126() { return 126; }
  int f127() { return 127; }
  int f128() { return 128; }
  int f129() { return 129; }
  int f130() { return 130; }
  int f131() { return 131; }
  int f132() { return 132; }
  int f133() { return 133; }
  int f134() { return 134; }
  int f135() { return 135; }
  int f136() { return 136; }
  int f137() { return 137; }
  int f138() { return 138; }
  int f139() { return 139; }
  int f140() { return 140; }
  int f141() { return 141; }
  int f142() { return 142; }
  int f143() { return 143; }
  int f144() { return 144; }
  int f145() { return 145; }
  int f146() { return 146; }
  int f147() { return 147; }
  int f148() { return 148; }
  int f149() { return 149; }
  int f150() { return 150; }
  int f151() { return 151; }
  int f152() { return 152; }
  int f153() { return 153; }
  int f154() { return 154; }
  int f155() { return 155; }
  int f156() { return 156; }
  int f157() { return 157; }
  int f158() { return 158; }
  int f159() { return 159; }
  int f160() { return 160; }
  int f161() { return 161; }
  int f162() { return 162; }
  int f163() { return 163; }
  int f164() { return 164; }
  int f165() { return 165; }
  int f166() { return 166; }
  int f167() { return 167; }
  int f168() { return 168; }
  int f169() { return 169; }
  int f170() { return 170; }
  int f171() { return 171; }
  int f172() { return 172; }
  int f173() { return 173; }
  int f174() { return 174; }
  int f175() { return 175; }
  int f176() { return 176; }
  int f177() { return 177; }
  int f178() { return 178; }
  int f179() { return 179; }
  int f180() { return 180; }
  int f181() { return 181; }
  int f182() { return 182; }
  int f183() { return 183; }
  int f184() { return 184; }
  int f185() { return 185; }
  int f186() { return 186; }
  int f187() { return 187; }
  int f188() { return 188; }
  int f189() { return 189; }
  int f190() { return 190; }
  int f191() { return 191; }
  int f192() { return 192; }
  int f193() { return 193; }
  int f194() { return 194; }
  int f195() { return 195; }
  int f196() { return 196; }
  int f197() { return 197; }
  int f198() { return 198; }
  int f199() { return 199; }
  int f200() { return 200; }
  int f201() { return 201; }
  int f202() { return 202; }
  int f203() { return 203; }
  int f204() { return 204; }
  int f205() { return 205; }
  int f206() { return 206; }
  int f207() { return 207; }
  int f208() { return 208; }
  int f209() { return 209; }
  int f210() { return 210; }
  int f211() { return 211; }
  int f212() { return 212; }
  int f213() { return 213; }
  int f214() { return 214; }
  int f215() { return 215; }
  int f216() { return 216; }
  int f217() { return 217; }
  int f218() { return 218; }
  int f219() { return 219; }
  int f220() { return 220; }
  int f221() { return 221; }
  int f222() { return 222; }
  int f223() { return 223; }
  int f224() { return 224; }
  int f225() { return 225; }
  int f226() { return 226; }
  int f227() { return 227; }
  int f228() { return 228; }
  int f229() { return 229; }
  int f230() { return 230; }
  int f231() { return 231; }
  int f232() { return 232; }
  int f233() { return 233; }
  int f234() { return 234; }
  int f235() { return 235; }
  int f236() { return 236; }
  int f237() { return 237; }
  int f238() { return 238; }
  int f239() { return 239; }
  int f240() { return 240; }
  int f241() { return 241; }
  int f242() { return 242; }
  int f243() { return 243; }
  int f244() { return 244; }
  int f245() { return 245; }
  int f246() { return 246; }
  int f247() { return 247; }
  int f248() { return 248; }
  int f249() { return 249; }
  int f250() { return 250; }
  int f251() { return 251; }
  int f252() { return 252; }
  int f253() { return 253; }
  int f254() { return 254; }
  int f255() { return 255; }
  int f256() { return 256; }
  int f257() { return 257; }
  int f258() { return 258; }
  int f259() { return 259; }
  int f260() { return 260; }
  int f261() { return 261; }
  int f262() { return 262; }
  int f263() { return 263; }
  int f264() { return 264; }
  int f265() { return 265; }
  int f266() { return 266; }
  int f267() { return 267; }
  int f268() { return 268; }
  int f269() { return 269; }
  int f270() { return 270; }
  int f271() { return 271; }
  int f272() { return 272; }
  int f273() { return 273; }
  int f274() { return 274; }
  int f275() { return 275; }
  int f276() { return 276; }
  int f277() { return 277; }
  int f278() { return 278; }
  int f279() { return 279; }
  int f280() { return 280; }
  int f281() { return 281; }
  int f282() { return 282; }
  int f283() { return 283; }
  int f284() { return 284; }
  int f285() { return 285; }
  int f286() { return 286; }
  int f287() { return 287; }
  int f288() { return 288; }
  int f289() { return 289; }
  int f290() { return 290; }
  int f291() { return 291; }
  int f292() { return 292; }
  int f293() { return 293; }
  int f294() { return 294; }
  int f295() { return 295; }
  int f296() { return 296; }
  int f297() { return 297; }
  int f298() { return 298; }
  int f299() { return 299; }
  int f300() { return 300; }
  int f301() { return 301; }
  int f302() { return 302; }
  int f303() { return 303; }
  int f304() { return 304; }
  int f305() { return 305; }
  int f306() { return 306; }
  int f307() { return 307; }
  int f308() { return 308; }
  int f309() { return 309; }
  int f310() { return 310; }
  int f311() { return 311; }
  int f312() { return 312; }
  int f313() { return 313; }
  int f314() { return 314; }
  int f315() { return 315; }
  int f316() { return 316; }
  int f317() { return 317; }
  int f318() { return 318; }
  int f319() { return 319; }
  int f320() { return 320; }
  int f321() { return 321; }
  int f322() { return 322; }
  int f323() { return 323; }
  int f324() { return 324; }
  int f325() { return 325; }
  int f326() { return 326; }
  int f327() { return 327; }
  int f328() { return 328; }
  int f329() { return 329; }
  int f330() { return 330; }
  int f331() { return 331; }
  int f332() { return 332; }
  int f333() { return 333; }
  int f334() { return 334; }
  int f335() { return 335; }
  int f336() { return 336; }
  int f337() { return 337; }
  int f338() { return 338; }
  int f339() { return 339; }
  int f340() { return 340; }
  int f341() { return 341; }
  int f342() { return 342; }
  int f343() { return 343; }
  int f344() { return 344; }
  int f345() { return 345; }
  int f346() { return 346; }
  int f347() { return 347; }
  int f348() { return 348; }
  int f349() { return 349; }
  int f350() { return 350; }
  int f351() { return 351; }
  int f352() { return 352; }
  int f353() { return 353; }
  int f354() { return 354; }
  int f355() { return 355; }
  int f356() { return 356; }
  int f357() { return 357; }
  int f358() { return 358; }
  int f359() { return 359; }
  int f360() { return 360; }
  int f361() { return 361; }
  int f362() { return 362; }
  int f363() { return 363; }
  int f364() { return 364; }
  int f365() { return 365; }
  int f366() { return 366; }
  int f367() { return 367; }
  int f368() { return 368; }
  int f369() { return 369; }
  int f370() { return 370; }
  int f371() { return 371; }
  int f372() { return 372; }
  int f373() { return 373; }
  int f374() { return 374; }
  int f375() { return 375; }
  int f376() { return 376; }
  int f377() { return 377; }
  int f378() { return 378; }
  int f379() { return 379; }
  int f380() { return 380; }
  int f381() { return 381; }
  int f382() { return 382; }
  int f383() { return 383; }
  int f384() { return 384; }
  int f385() { return 385; }
  int f386() { return 386; }
  int f387() { return 387; }
  int f388() { return 388; }
  int f389() { return 389; }
  int f390() { return 390; }
  int f391() { return 391; }
  int f392() { return 392; }
  int f393() { return 393; }
  int f394() { return 394; }
  int f395() { return 395; }
  int f396() { return 396; }
  int f397() { return 397; }
  int f398() { return 398; }
  int f399() { return 399; }
  int f400() { return 400; }
  int f401() { return 401; }
  int f402() { return 402; }
  int f403() { return 403; }
  int f404() { return 404; }
  int f405() { return 405; }
  int f406() { return 406; }
  int f407() { return 407; }
  int f408() { return 408; }
  int f409() { return 409; }
  int f410() { return 410; }
  int f411() { return 411; }
  int f412() { return 412; }
  int f413() { return 413; }
  int f414() { return 414; }
  int f415() { return 415; }
  int f416() { return 416; }
  int f417() { return 417; }
  int f418() { return 418; }
  int f419() { return 419; }
  int f420() { return 420; }
  int f421() { return 421; }
  int f422() { return 422; }
  int f423() { return 423; }
  int f424() { return 424; }
  int f425() { return 425; }
  int f426() { return 426; }
  int f427() { return 427; }
  int f428() { return 428; }
  int f429() { return 429; }
  int f430() { return 430; }
  int f431() { return 431; }
  int f432() { return 432; }
  int f433() { return 433; }
  int f434() { return 434; }
  int f435() { return 435; }
  int f436() { return 436; }
  int f437() { return 437; }
  int f438() { return 438; }
  int f439() { return 439; }
  int f440() { return 440; }
  int f441() { return 441; }
  int f442() { return 442; }
  int f443() { return 443; }
  int f444() { return 444; }
  int f445() { return 445; }
  int f446() { return 446; }
  int f447() { return 447; }
  int f448() { return 448; }
  int f449() { return 449; }
  int f450() { return 450; }
  int f451() { return 451; }
  int f452() { return 452; }
  int f453() { return 453; }
  int f454() { return 454; }
  int f455() { return 455; }
  int f456() { return 456; }
  int f457() { return 457; }
  int f458() { return 458; }
  int f459() { return 459; }
  int f460() { return 460; }
  int f461() { return 461; }
  int f462() { return 462; }
  int f463() { return 463; }
  int f464() { return 464; }
  int f465() { return 465; }
  int f466() { return 466; }
  int f467() { return 467; }
  int f468() { return 468; }
  int f469() { return 469; }
  int f470() { return 470; }
  int f471() { return 471; }
  int f472() { return 472; }
  int f473() { return 473; }
  int f474() { return 474; }
  int f475() { return 475; }
  int f476() { return 476; }
  int f477() { return 477; }
  int f478() { return 478; }
  int f479() { return 479; }
  int f480() { return 480; }
  int f481() { return 481; }
  int f482() { return 482; }
  int f483() { return 483; }
  int f484() { return 484; }
  int f485() { return 485; }
  int f486() { return 486; }
  int f487() { return 487; }
  int f488() { return 488; }
  int f489() { return 489; }
  int f490() { return 490; }
  int f491() { return 491; }
  int f492() { return 492; }
  int f493() { return 493; }
  int f494() { return 494; }
  int f495() { return 495; }
  int f496() { return 496; }
  int f497() { return 497; }
  int f498() { return 498; }
  int f499() { return 499; }

}

void test() {
	C c = new C();
	assert(c.f0() == 0);
	assert(c.f1() == 1);
	assert(c.f2() == 2);
	assert(c.f3() == 3);
	assert(c.f4() == 4);
	assert(c.f5() == 5);
	assert(c.f6() == 6);
	assert(c.f7() == 7);
	assert(c.f8() == 8);
	assert(c.f9() == 9);
	assert(c.f10() == 10);
	assert(c.f11() == 11);
	assert(c.f12() == 12);
	assert(c.f13() == 13);
	assert(c.f14() == 14);
	assert(c.f15() == 15);
	assert(c.f16() == 16);
	assert(c.f17() == 17);
	assert(c.f18() == 18);
	assert(c.f19() == 19);
	assert(c.f20() == 20);
	assert(c.f21() == 21);
	assert(c.f22() == 22);
	assert(c.f23() == 23);
	assert(c.f24() == 24);
	assert(c.f25() == 25);
	assert(c.f26() == 26);
	assert(c.f27() == 27);
	assert(c.f28() == 28);
	assert(c.f29() == 29);
	assert(c.f30() == 30);
	assert(c.f31() == 31);
	assert(c.f32() == 32);
	assert(c.f33() == 33);
	assert(c.f34() == 34);
	assert(c.f35() == 35);
	assert(c.f36() == 36);
	assert(c.f37() == 37);
	assert(c.f38() == 38);
	assert(c.f39() == 39);
	assert(c.f40() == 40);
	assert(c.f41() == 41);
	assert(c.f42() == 42);
	assert(c.f43() == 43);
	assert(c.f44() == 44);
	assert(c.f45() == 45);
	assert(c.f46() == 46);
	assert(c.f47() == 47);
	assert(c.f48() == 48);
	assert(c.f49() == 49);
	assert(c.f50() == 50);
	assert(c.f51() == 51);
	assert(c.f52() == 52);
	assert(c.f53() == 53);
	assert(c.f54() == 54);
	assert(c.f55() == 55);
	assert(c.f56() == 56);
	assert(c.f57() == 57);
	assert(c.f58() == 58);
	assert(c.f59() == 59);
	assert(c.f60() == 60);
	assert(c.f61() == 61);
	assert(c.f62() == 62);
	assert(c.f63() == 63);
	assert(c.f64() == 64);
	assert(c.f65() == 65);
	assert(c.f66() == 66);
	assert(c.f67() == 67);
	assert(c.f68() == 68);
	assert(c.f69() == 69);
	assert(c.f70() == 70);
	assert(c.f71() == 71);
	assert(c.f72() == 72);
	assert(c.f73() == 73);
	assert(c.f74() == 74);
	assert(c.f75() == 75);
	assert(c.f76() == 76);
	assert(c.f77() == 77);
	assert(c.f78() == 78);
	assert(c.f79() == 79);
	assert(c.f80() == 80);
	assert(c.f81() == 81);
	assert(c.f82() == 82);
	assert(c.f83() == 83);
	assert(c.f84() == 84);
	assert(c.f85() == 85);
	assert(c.f86() == 86);
	assert(c.f87() == 87);
	assert(c.f88() == 88);
	assert(c.f89() == 89);
	assert(c.f90() == 90);
	assert(c.f91() == 91);
	assert(c.f92() == 92);
	assert(c.f93() == 93);
	assert(c.f94() == 94);
	assert(c.f95() == 95);
	assert(c.f96() == 96);
	assert(c.f97() == 97);
	assert(c.f98() == 98);
	assert(c.f99() == 99);
	assert(c.f100() == 100);
	assert(c.f101() == 101);
	assert(c.f102() == 102);
	assert(c.f103() == 103);
	assert(c.f104() == 104);
	assert(c.f105() == 105);
	assert(c.f106() == 106);
	assert(c.f107() == 107);
	assert(c.f108() == 108);
	assert(c.f109() == 109);
	assert(c.f110() == 110);
	assert(c.f111() == 111);
	assert(c.f112() == 112);
	assert(c.f113() == 113);
	assert(c.f114() == 114);
	assert(c.f115() == 115);
	assert(c.f116() == 116);
	assert(c.f117() == 117);
	assert(c.f118() == 118);
	assert(c.f119() == 119);
	assert(c.f120() == 120);
	assert(c.f121() == 121);
	assert(c.f122() == 122);
	assert(c.f123() == 123);
	assert(c.f124() == 124);
	assert(c.f125() == 125);
	assert(c.f126() == 126);
	assert(c.f127() == 127);
	assert(c.f128() == 128);
	assert(c.f129() == 129);
	assert(c.f130() == 130);
	assert(c.f131() == 131);
	assert(c.f132() == 132);
	assert(c.f133() == 133);
	assert(c.f134() == 134);
	assert(c.f135() == 135);
	assert(c.f136() == 136);
	assert(c.f137() == 137);
	assert(c.f138() == 138);
	assert(c.f139() == 139);
	assert(c.f140() == 140);
	assert(c.f141() == 141);
	assert(c.f142() == 142);
	assert(c.f143() == 143);
	assert(c.f144() == 144);
	assert(c.f145() == 145);
	assert(c.f146() == 146);
	assert(c.f147() == 147);
	assert(c.f148() == 148);
	assert(c.f149() == 149);
	assert(c.f150() == 150);
	assert(c.f151() == 151);
	assert(c.f152() == 152);
	assert(c.f153() == 153);
	assert(c.f154() == 154);
	assert(c.f155() == 155);
	assert(c.f156() == 156);
	assert(c.f157() == 157);
	assert(c.f158() == 158);
	assert(c.f159() == 159);
	assert(c.f160() == 160);
	assert(c.f161() == 161);
	assert(c.f162() == 162);
	assert(c.f163() == 163);
	assert(c.f164() == 164);
	assert(c.f165() == 165);
	assert(c.f166() == 166);
	assert(c.f167() == 167);
	assert(c.f168() == 168);
	assert(c.f169() == 169);
	assert(c.f170() == 170);
	assert(c.f171() == 171);
	assert(c.f172() == 172);
	assert(c.f173() == 173);
	assert(c.f174() == 174);
	assert(c.f175() == 175);
	assert(c.f176() == 176);
	assert(c.f177() == 177);
	assert(c.f178() == 178);
	assert(c.f179() == 179);
	assert(c.f180() == 180);
	assert(c.f181() == 181);
	assert(c.f182() == 182);
	assert(c.f183() == 183);
	assert(c.f184() == 184);
	assert(c.f185() == 185);
	assert(c.f186() == 186);
	assert(c.f187() == 187);
	assert(c.f188() == 188);
	assert(c.f189() == 189);
	assert(c.f190() == 190);
	assert(c.f191() == 191);
	assert(c.f192() == 192);
	assert(c.f193() == 193);
	assert(c.f194() == 194);
	assert(c.f195() == 195);
	assert(c.f196() == 196);
	assert(c.f197() == 197);
	assert(c.f198() == 198);
	assert(c.f199() == 199);
	assert(c.f200() == 200);
	assert(c.f201() == 201);
	assert(c.f202() == 202);
	assert(c.f203() == 203);
	assert(c.f204() == 204);
	assert(c.f205() == 205);
	assert(c.f206() == 206);
	assert(c.f207() == 207);
	assert(c.f208() == 208);
	assert(c.f209() == 209);
	assert(c.f210() == 210);
	assert(c.f211() == 211);
	assert(c.f212() == 212);
	assert(c.f213() == 213);
	assert(c.f214() == 214);
	assert(c.f215() == 215);
	assert(c.f216() == 216);
	assert(c.f217() == 217);
	assert(c.f218() == 218);
	assert(c.f219() == 219);
	assert(c.f220() == 220);
	assert(c.f221() == 221);
	assert(c.f222() == 222);
	assert(c.f223() == 223);
	assert(c.f224() == 224);
	assert(c.f225() == 225);
	assert(c.f226() == 226);
	assert(c.f227() == 227);
	assert(c.f228() == 228);
	assert(c.f229() == 229);
	assert(c.f230() == 230);
	assert(c.f231() == 231);
	assert(c.f232() == 232);
	assert(c.f233() == 233);
	assert(c.f234() == 234);
	assert(c.f235() == 235);
	assert(c.f236() == 236);
	assert(c.f237() == 237);
	assert(c.f238() == 238);
	assert(c.f239() == 239);
	assert(c.f240() == 240);
	assert(c.f241() == 241);
	assert(c.f242() == 242);
	assert(c.f243() == 243);
	assert(c.f244() == 244);
	assert(c.f245() == 245);
	assert(c.f246() == 246);
	assert(c.f247() == 247);
	assert(c.f248() == 248);
	assert(c.f249() == 249);
	assert(c.f250() == 250);
	assert(c.f251() == 251);
	assert(c.f252() == 252);
	assert(c.f253() == 253);
	assert(c.f254() == 254);
	assert(c.f255() == 255);
	assert(c.f256() == 256);
	assert(c.f257() == 257);
	assert(c.f258() == 258);
	assert(c.f259() == 259);
	assert(c.f260() == 260);
	assert(c.f261() == 261);
	assert(c.f262() == 262);
	assert(c.f263() == 263);
	assert(c.f264() == 264);
	assert(c.f265() == 265);
	assert(c.f266() == 266);
	assert(c.f267() == 267);
	assert(c.f268() == 268);
	assert(c.f269() == 269);
	assert(c.f270() == 270);
	assert(c.f271() == 271);
	assert(c.f272() == 272);
	assert(c.f273() == 273);
	assert(c.f274() == 274);
	assert(c.f275() == 275);
	assert(c.f276() == 276);
	assert(c.f277() == 277);
	assert(c.f278() == 278);
	assert(c.f279() == 279);
	assert(c.f280() == 280);
	assert(c.f281() == 281);
	assert(c.f282() == 282);
	assert(c.f283() == 283);
	assert(c.f284() == 284);
	assert(c.f285() == 285);
	assert(c.f286() == 286);
	assert(c.f287() == 287);
	assert(c.f288() == 288);
	assert(c.f289() == 289);
	assert(c.f290() == 290);
	assert(c.f291() == 291);
	assert(c.f292() == 292);
	assert(c.f293() == 293);
	assert(c.f294() == 294);
	assert(c.f295() == 295);
	assert(c.f296() == 296);
	assert(c.f297() == 297);
	assert(c.f298() == 298);
	assert(c.f299() == 299);
	assert(c.f300() == 300);
	assert(c.f301() == 301);
	assert(c.f302() == 302);
	assert(c.f303() == 303);
	assert(c.f304() == 304);
	assert(c.f305() == 305);
	assert(c.f306() == 306);
	assert(c.f307() == 307);
	assert(c.f308() == 308);
	assert(c.f309() == 309);
	assert(c.f310() == 310);
	assert(c.f311() == 311);
	assert(c.f312() == 312);
	assert(c.f313() == 313);
	assert(c.f314() == 314);
	assert(c.f315() == 315);
	assert(c.f316() == 316);
	assert(c.f317() == 317);
	assert(c.f318() == 318);
	assert(c.f319() == 319);
	assert(c.f320() == 320);
	assert(c.f321() == 321);
	assert(c.f322() == 322);
	assert(c.f323() == 323);
	assert(c.f324() == 324);
	assert(c.f325() == 325);
	assert(c.f326() == 326);
	assert(c.f327() == 327);
	assert(c.f328() == 328);
	assert(c.f329() == 329);
	assert(c.f330() == 330);
	assert(c.f331() == 331);
	assert(c.f332() == 332);
	assert(c.f333() == 333);
	assert(c.f334() == 334);
	assert(c.f335() == 335);
	assert(c.f336() == 336);
	assert(c.f337() == 337);
	assert(c.f338() == 338);
	assert(c.f339() == 339);
	assert(c.f340() == 340);
	assert(c.f341() == 341);
	assert(c.f342() == 342);
	assert(c.f343() == 343);
	assert(c.f344() == 344);
	assert(c.f345() == 345);
	assert(c.f346() == 346);
	assert(c.f347() == 347);
	assert(c.f348() == 348);
	assert(c.f349() == 349);
	assert(c.f350() == 350);
	assert(c.f351() == 351);
	assert(c.f352() == 352);
	assert(c.f353() == 353);
	assert(c.f354() == 354);
	assert(c.f355() == 355);
	assert(c.f356() == 356);
	assert(c.f357() == 357);
	assert(c.f358() == 358);
	assert(c.f359() == 359);
	assert(c.f360() == 360);
	assert(c.f361() == 361);
	assert(c.f362() == 362);
	assert(c.f363() == 363);
	assert(c.f364() == 364);
	assert(c.f365() == 365);
	assert(c.f366() == 366);
	assert(c.f367() == 367);
	assert(c.f368() == 368);
	assert(c.f369() == 369);
	assert(c.f370() == 370);
	assert(c.f371() == 371);
	assert(c.f372() == 372);
	assert(c.f373() == 373);
	assert(c.f374() == 374);
	assert(c.f375() == 375);
	assert(c.f376() == 376);
	assert(c.f377() == 377);
	assert(c.f378() == 378);
	assert(c.f379() == 379);
	assert(c.f380() == 380);
	assert(c.f381() == 381);
	assert(c.f382() == 382);
	assert(c.f383() == 383);
	assert(c.f384() == 384);
	assert(c.f385() == 385);
	assert(c.f386() == 386);
	assert(c.f387() == 387);
	assert(c.f388() == 388);
	assert(c.f389() == 389);
	assert(c.f390() == 390);
	assert(c.f391() == 391);
	assert(c.f392() == 392);
	assert(c.f393() == 393);
	assert(c.f394() == 394);
	assert(c.f395() == 395);
	assert(c.f396() == 396);
	assert(c.f397() == 397);
	assert(c.f398() == 398);
	assert(c.f399() == 399);
	assert(c.f400() == 400);
	assert(c.f401() == 401);
	assert(c.f402() == 402);
	assert(c.f403() == 403);
	assert(c.f404() == 404);
	assert(c.f405() == 405);
	assert(c.f406() == 406);
	assert(c.f407() == 407);
	assert(c.f408() == 408);
	assert(c.f409() == 409);
	assert(c.f410() == 410);
	assert(c.f411() == 411);
	assert(c.f412() == 412);
	assert(c.f413() == 413);
	assert(c.f414() == 414);
	assert(c.f415() == 415);
	assert(c.f416() == 416);
	assert(c.f417() == 417);
	assert(c.f418() == 418);
	assert(c.f419() == 419);
	assert(c.f420() == 420);
	assert(c.f421() == 421);
	assert(c.f422() == 422);
	assert(c.f423() == 423);
	assert(c.f424() == 424);
	assert(c.f425() == 425);
	assert(c.f426() == 426);
	assert(c.f427() == 427);
	assert(c.f428() == 428);
	assert(c.f429() == 429);
	assert(c.f430() == 430);
	assert(c.f431() == 431);
	assert(c.f432() == 432);
	assert(c.f433() == 433);
	assert(c.f434() == 434);
	assert(c.f435() == 435);
	assert(c.f436() == 436);
	assert(c.f437() == 437);
	assert(c.f438() == 438);
	assert(c.f439() == 439);
	assert(c.f440() == 440);
	assert(c.f441() == 441);
	assert(c.f442() == 442);
	assert(c.f443() == 443);
	assert(c.f444() == 444);
	assert(c.f445() == 445);
	assert(c.f446() == 446);
	assert(c.f447() == 447);
	assert(c.f448() == 448);
	assert(c.f449() == 449);
	assert(c.f450() == 450);
	assert(c.f451() == 451);
	assert(c.f452() == 452);
	assert(c.f453() == 453);
	assert(c.f454() == 454);
	assert(c.f455() == 455);
	assert(c.f456() == 456);
	assert(c.f457() == 457);
	assert(c.f458() == 458);
	assert(c.f459() == 459);
	assert(c.f460() == 460);
	assert(c.f461() == 461);
	assert(c.f462() == 462);
	assert(c.f463() == 463);
	assert(c.f464() == 464);
	assert(c.f465() == 465);
	assert(c.f466() == 466);
	assert(c.f467() == 467);
	assert(c.f468() == 468);
	assert(c.f469() == 469);
	assert(c.f470() == 470);
	assert(c.f471() == 471);
	assert(c.f472() == 472);
	assert(c.f473() == 473);
	assert(c.f474() == 474);
	assert(c.f475() == 475);
	assert(c.f476() == 476);
	assert(c.f477() == 477);
	assert(c.f478() == 478);
	assert(c.f479() == 479);
	assert(c.f480() == 480);
	assert(c.f481() == 481);
	assert(c.f482() == 482);
	assert(c.f483() == 483);
	assert(c.f484() == 484);
	assert(c.f485() == 485);
	assert(c.f486() == 486);
	assert(c.f487() == 487);
	assert(c.f488() == 488);
	assert(c.f489() == 489);
	assert(c.f490() == 490);
	assert(c.f491() == 491);
	assert(c.f492() == 492);
	assert(c.f493() == 493);
	assert(c.f494() == 494);
	assert(c.f495() == 495);
	assert(c.f496() == 496);
	assert(c.f497() == 497);
	assert(c.f498() == 498);
	assert(c.f499() == 499);

}

test();
