K.import("konoha");

class A0 {
    int x0;
}

class A1 extends A0 {
    int i1;
    A0 o1;
}

class A2 extends A1 {
    int i2;
    A1 o2;
}

class A3 extends A2 {
    int i3;
    A2 o3;
}

class A4 extends A3 {
    int i4;
    A3 o4;
}

class A5 extends A4 {
    int i5;
    A4 o5;
}

class A6 extends A5 {
    int i6;
    A5 o6;
}

class A7 extends A6 {
    int i7;
    A6 o7;
}

class A8 extends A7 {
    int i8;
    A7 o8;
}

