//Written by Joseph
//import("konoha.new"); Don't use this
import("dscript.subproc");

void test() {
	// assert(Subproc.checkOutput("echo fuga") == "fuga\n");
	// assert(Subproc.checkOutput("echo \"hoge\"") == "\"hoge\"\n");

	// Subproc s = new Subproc("ls", false);
	// assert(s.checkOutput("echo hello") == "hello\n");
	// s.bg();
	// //after execution
	// assert(s.checkOutput("echo \"hi\"") == "\"hi\"\n");
}

test();
