import("JavaStyle.Object");
import("MiniKonoha.Map");
import("Syntax.GlobalVariable");
import("Syntax.Null");

JQuery jQuery(String selector){ return null; }
JQuery jQuery(String selector, Object context){ return null; }
JQuery jQuery(Object element){ return null; }
JQuery jQuery(Map[Object] map){ return null; }
JQuery jQuery(Object[] elementArray){ return null; }
JQuery jQuery(JQuery object){ return null; }
JQuery jQuery(Func func){ return null; }
JQuery jQuery(){ return null; }

