#define To_charPtr(sfp) S_totext(sfp.asString)
#define To_charPtrPtr(sfp) NULL
#define To_int(sfp) sfp.intValue
#define To_intPtr(sfp)     NULL
#define To_size_t(sfp)     sfp.intValue
#define To_size_tPtr(sfp)  NULL
#define To_unsigned_charPtr(sfp) S_totext(sfp.asString)
#define To_unsigned_int(sfp) sfp.intValue    sfp.intValue
#define To_unsigned_intPtr(sfp)
#define To_unsigned_long(sfp) sfp.intValue
#define To_unsigned_long_Ptr(sfp)
#define To_unsigned_long_long(sfp) sfp.intValue
#define To_unsigned_long_long_Ptr(sfp)
#define To_virConnectAuthPtr(sfp)
#define To_virConnectCloseFunc(sfp)
#define To_virConnectDomainEventCallback(sfp)
#define To_virConnectDomainEventGenericCallback(sfp)
#define To_virConnectPtr(sfp) RawPtr(virConnectPtr, sfp.asObject)
#define To_virDomainNodeInfoPtr(sfp)
#define To_virDomainNodeJobInfoPtr(sfp)
#define To_virDomainNodeStatsPtr(sfp)
#define To_virDomainControlInfoPtr(sfp)
#define To_virDomainDiskErrorPtr(sfp)
#define To_virDomainInfoPtr(sfp)
#define To_virDomainInterfaceStatsPtr(sfp)
#define To_virDomainJobInfoPtr(sfp)
#define To_virDomainMemoryStatPtr(sfp)
#define To_virDomainPtr(sfp)
#define To_virDomainPtrPtrPtr(sfp)
#define To_virDomainSnapshotPtr(sfp)
#define To_virDomainSnapshotPtrPtrPtr(sfp)
#define To_virEventAddHandleFunc(sfp)
#define To_virEventAddTimeoutFunc(sfp)
#define To_virEventHandleCallback(sfp)
#define To_virEventRemoveHandleFunc(sfp)
#define To_virEventRemoveTimeoutFunc(sfp)
#define To_virEventTimeoutCallback(sfp)
#define To_virEventUpdateHandleFunc(sfp)
#define To_virEventUpdateTimeoutFunc(sfp)
#define To_virFreeCallback(sfp)
#define To_virInterfacePtr(sfp)
#define To_virInterfacePtrPtrPtr(sfp)
#define To_virNWFilterPtr(sfp)
#define To_virNWFilterPtrPtrPtr(sfp)
#define To_virNetworkPtr(sfp)
#define To_virNetworkPtrPtrPtr(sfp)
#define To_virNodeCPUStatsPtr(sfp)
#define To_virNodeDevicePtr(sfp)
#define To_virNodeDevicePtrPtrPtr(sfp)
#define To_virNodeInfoPtr(sfp)
#define To_virNodeMemoryStatsPtr(sfp)
#define To_virSecretPtr(sfp)
#define To_virSecretPtrPtrPtr(sfp)
#define To_virSecurityLabelPtr(sfp)
#define To_virSecurityLabelPtrPtr(sfp)
#define To_virSecurityModelPtr(sfp)
#define To_virStoragePoolInfoPtr(sfp)
#define To_virStoragePoolPtr(sfp)
#define To_virStoragePoolPtrPtrPtr(sfp)
#define To_virStorageVolInfoPtr(sfp)
#define To_virStorageVolPtr(sfp)
#define To_virStorageVolPtrPtrPtr(sfp)
#define To_virStreamEventCallback(sfp)
#define To_virStreamPtr(sfp)
#define To_virStreamSinkFunc(sfp)
#define To_virStreamSourceFunc(sfp)
#define To_virTypedParameterPtr(sfp)
#define To_virVcpuInfoPtr(sfp)
#define To_voidPtr(sfp) NULL
