// written by kimio

boolean isTrue() {
	return true;
}

boolean isFalse() {
	return false;
}

void test() {
	boolean btrue = true;
	boolean bfalse = false;
	int a = 1;
	System.p(true);
	System.p(false);
	System.p(btrue);
	System.p(bfalse);
	System.p(a < 2);
	System.p(a > 2);
	System.p(isTrue());
	System.p(isFalse());
	System.p(btrue == true);
	System.p(btrue == false);
	System.p(bfalse == true);
	System.p(btrue == false);
}

test()

