// written by imasahiro
import("ijit");

void f() {
    int x = 10;
    int y = 10;
    boolean v_false = false;
    int z = x + y;
    int w = x - y;
    int a = x * y;
    int b = x / y;
    int c = x % y;
    boolean d = x == y;
    boolean e = x != y;
    boolean f = x < y;
    boolean g = x <= y;
    boolean h = x > y;
    boolean i = x >= y;
    //int j = x & y;
    //int k = x | y;
    //int l = x ^ y;
    //int m = x << y;
    //int n = x >> y;
    boolean o = !v_false;
    int p = -x;
    System.p(z);
}
f();
