/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_GreenTeaScript_MiniKonohaExecutor */

#ifndef _Included_org_GreenTeaScript_MiniKonohaExecutor
#define _Included_org_GreenTeaScript_MiniKonohaExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_GreenTeaScript_MiniKonohaExecutor
 * Method:    MiniKonohaExecute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_GreenTeaScript_MiniKonohaExecutor_MiniKonohaExecute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
