// written by kimio kuramitsu

//import("konoha.new"); Don't use this
import("Syntax.JavaStyleClass");

class C {
	int a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0;
	int l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0;
	int w0, x0, y0, z0;
	int a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1;
	int l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1;
	int w1, x1, y1, z1;
	int a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2;
	int l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2;
	int w2, x2, y2, z2;
	int a3, b3, c3, d3, e3, f3, g3, h3, i3, j3, k3;
	int l3, m3, n3, o3, p3, q3, r3, s3, t3, u3, v3;
	int w3, x3, y3, z3;
	int a4, b4, c4, d4, e4, f4, g4, h4, i4, j4, k4;
	int l4, m4, n4, o4, p4, q4, r4, s4, t4, u4, v4;
	int w4, x4, y4, z4;
	int a5, b5, c5, d5, e5, f5, g5, h5, i5, j5, k5;
	int l5, m5, n5, o5, p5, q5, r5, s5, t5, u5, v5;
	int w5, x5, y5, z5;
	int a6, b6, c6, d6, e6, f6, g6, h6, i6, j6, k6;
	int l6, m6, n6, o6, p6, q6, r6, s6, t6, u6, v6;
	int w6, x6, y6, z6;
	int a7, b7, c7, d7, e7, f7, g7, h7, i7, j7, k7;
	int l7, m7, n7, o7, p7, q7, r7, s7, t7, u7, v7;
	int w7, x7, y7, z7;
	int a8, b8, c8, d8, e8, f8, g8, h8, i8, j8, k8;
	int l8, m8, n8, o8, p8, q8, r8, s8, t8, u8, v8;
	int w8, x8, y8, z8;
	int a9, b9, c9, d9, e9, f9, g9, h9, i9, j9, k9;
	int l9, m9, n9, o9, p9, q9, r9, s9, t9, u9, v9;
	int w9, x9, y9, z9;
	C() {}
}
void test() {
	C c = new C();
	assert(c.a0 == 0);
	assert(c.z9 == 0);
}

test();

