// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C0 {
	int x0;
	C0() {}
}

class C1 extends C0 {
	int x1;
}

class C2 extends C1 {
	int x2;
}

class C3 extends C2 {
	int x3;
}

class C4 extends C3 {
	int x4;
}

class C5 extends C4 {
	int x5;
}

class C6 extends C5 {
	int x6;
}

class C7 extends C6 {
	int x7;
}

class C8 extends C7 {
	int x8;
}

class C9 extends C8 {
	int x9;
}

class C10 extends C9 {
	int x10;
}

class C11 extends C10 {
	int x11;
}

class C12 extends C11 {
	int x12;
}

class C13 extends C12 {
	int x13;
}

class C14 extends C13 {
	int x14;
}

class C15 extends C14 {
	int x15;
}

class C16 extends C15 {
	int x16;
}

class C17 extends C16 {
	int x17;
}

class C18 extends C17 {
	int x18;
}

class C19 extends C18 {
	int x19;
}

class C20 extends C19 {
	int x20;
}

class C21 extends C20 {
	int x21;
}

class C22 extends C21 {
	int x22;
}

class C23 extends C22 {
	int x23;
}

class C24 extends C23 {
	int x24;
}

class C25 extends C24 {
	int x25;
}

class C26 extends C25 {
	int x26;
}

class C27 extends C26 {
	int x27;
}

class C28 extends C27 {
	int x28;
}

class C29 extends C28 {
	int x29;
}

class C30 extends C29 {
	int x30;
}

class C31 extends C30 {
	int x31;
}

class C32 extends C31 {
	int x32;
}

class C33 extends C32 {
	int x33;
}

class C34 extends C33 {
	int x34;
}

class C35 extends C34 {
	int x35;
}

class C36 extends C35 {
	int x36;
}

class C37 extends C36 {
	int x37;
}

class C38 extends C37 {
	int x38;
}

class C39 extends C38 {
	int x39;
}

class C40 extends C39 {
	int x40;
}

class C41 extends C40 {
	int x41;
}

class C42 extends C41 {
	int x42;
}

class C43 extends C42 {
	int x43;
}

class C44 extends C43 {
	int x44;
}

class C45 extends C44 {
	int x45;
}

class C46 extends C45 {
	int x46;
}

class C47 extends C46 {
	int x47;
}

class C48 extends C47 {
	int x48;
}

class C49 extends C48 {
	int x49;
}

class C50 extends C49 {
	int x50;
}

class C51 extends C50 {
	int x51;
}

class C52 extends C51 {
	int x52;
}

class C53 extends C52 {
	int x53;
}

class C54 extends C53 {
	int x54;
}

class C55 extends C54 {
	int x55;
}

class C56 extends C55 {
	int x56;
}

class C57 extends C56 {
	int x57;
}

class C58 extends C57 {
	int x58;
}

class C59 extends C58 {
	int x59;
}

class C60 extends C59 {
	int x60;
}

class C61 extends C60 {
	int x61;
}

class C62 extends C61 {
	int x62;
}

class C63 extends C62 {
	int x63;
}

class C64 extends C63 {
	int x64;
}

class C65 extends C64 {
	int x65;
}

class C66 extends C65 {
	int x66;
}

class C67 extends C66 {
	int x67;
}

class C68 extends C67 {
	int x68;
}

class C69 extends C68 {
	int x69;
}

class C70 extends C69 {
	int x70;
}

class C71 extends C70 {
	int x71;
}

class C72 extends C71 {
	int x72;
}

class C73 extends C72 {
	int x73;
}

class C74 extends C73 {
	int x74;
}

class C75 extends C74 {
	int x75;
}

class C76 extends C75 {
	int x76;
}

class C77 extends C76 {
	int x77;
}

class C78 extends C77 {
	int x78;
}

class C79 extends C78 {
	int x79;
}

class C80 extends C79 {
	int x80;
}

class C81 extends C80 {
	int x81;
}

class C82 extends C81 {
	int x82;
}

class C83 extends C82 {
	int x83;
}

class C84 extends C83 {
	int x84;
}

class C85 extends C84 {
	int x85;
}

class C86 extends C85 {
	int x86;
}

class C87 extends C86 {
	int x87;
}

class C88 extends C87 {
	int x88;
}

class C89 extends C88 {
	int x89;
}

class C90 extends C89 {
	int x90;
}

class C91 extends C90 {
	int x91;
}

class C92 extends C91 {
	int x92;
}

class C93 extends C92 {
	int x93;
}

class C94 extends C93 {
	int x94;
}

class C95 extends C94 {
	int x95;
}

class C96 extends C95 {
	int x96;
}

class C97 extends C96 {
	int x97;
}

class C98 extends C97 {
	int x98;
}

class C99 extends C98 {
	int x99;
}


void test() {
	C99 c = new C99();
	assert(c.x0 == 0);
	assert(c.x1 == 0);
	assert(c.x2 == 0);
	assert(c.x3 == 0);
	assert(c.x4 == 0);
	assert(c.x5 == 0);
	assert(c.x6 == 0);
	assert(c.x7 == 0);
	assert(c.x8 == 0);
	assert(c.x9 == 0);
	assert(c.x10 == 0);
	assert(c.x11 == 0);
	assert(c.x12 == 0);
	assert(c.x13 == 0);
	assert(c.x14 == 0);
	assert(c.x15 == 0);
	assert(c.x16 == 0);
	assert(c.x17 == 0);
	assert(c.x18 == 0);
	assert(c.x19 == 0);
	assert(c.x20 == 0);
	assert(c.x21 == 0);
	assert(c.x22 == 0);
	assert(c.x23 == 0);
	assert(c.x24 == 0);
	assert(c.x25 == 0);
	assert(c.x26 == 0);
	assert(c.x27 == 0);
	assert(c.x28 == 0);
	assert(c.x29 == 0);
	assert(c.x30 == 0);
	assert(c.x31 == 0);
	assert(c.x32 == 0);
	assert(c.x33 == 0);
	assert(c.x34 == 0);
	assert(c.x35 == 0);
	assert(c.x36 == 0);
	assert(c.x37 == 0);
	assert(c.x38 == 0);
	assert(c.x39 == 0);
	assert(c.x40 == 0);
	assert(c.x41 == 0);
	assert(c.x42 == 0);
	assert(c.x43 == 0);
	assert(c.x44 == 0);
	assert(c.x45 == 0);
	assert(c.x46 == 0);
	assert(c.x47 == 0);
	assert(c.x48 == 0);
	assert(c.x49 == 0);
	assert(c.x50 == 0);
	assert(c.x51 == 0);
	assert(c.x52 == 0);
	assert(c.x53 == 0);
	assert(c.x54 == 0);
	assert(c.x55 == 0);
	assert(c.x56 == 0);
	assert(c.x57 == 0);
	assert(c.x58 == 0);
	assert(c.x59 == 0);
	assert(c.x60 == 0);
	assert(c.x61 == 0);
	assert(c.x62 == 0);
	assert(c.x63 == 0);
	assert(c.x64 == 0);
	assert(c.x65 == 0);
	assert(c.x66 == 0);
	assert(c.x67 == 0);
	assert(c.x68 == 0);
	assert(c.x69 == 0);
	assert(c.x70 == 0);
	assert(c.x71 == 0);
	assert(c.x72 == 0);
	assert(c.x73 == 0);
	assert(c.x74 == 0);
	assert(c.x75 == 0);
	assert(c.x76 == 0);
	assert(c.x77 == 0);
	assert(c.x78 == 0);
	assert(c.x79 == 0);
	assert(c.x80 == 0);
	assert(c.x81 == 0);
	assert(c.x82 == 0);
	assert(c.x83 == 0);
	assert(c.x84 == 0);
	assert(c.x85 == 0);
	assert(c.x86 == 0);
	assert(c.x87 == 0);
	assert(c.x88 == 0);
	assert(c.x89 == 0);
	assert(c.x90 == 0);
	assert(c.x91 == 0);
	assert(c.x92 == 0);
	assert(c.x93 == 0);
	assert(c.x94 == 0);
	assert(c.x95 == 0);
	assert(c.x96 == 0);
	assert(c.x97 == 0);
	assert(c.x98 == 0);
	assert(c.x99 == 0);

}

test();
