// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C0 {
	int x0;
	C0() {}
}

class C1 extends C0 {
	int x1;
}

class C2 extends C1 {
	int x2;
}

class C3 extends C2 {
	int x3;
}

class C4 extends C3 {
	int x4;
}

class C5 extends C4 {
	int x5;
}

class C6 extends C5 {
	int x6;
}

class C7 extends C6 {
	int x7;
}

class C8 extends C7 {
	int x8;
}

class C9 extends C8 {
	int x9;
}

class C10 extends C9 {
	int x10;
}

class C11 extends C10 {
	int x11;
}

class C12 extends C11 {
	int x12;
}

class C13 extends C12 {
	int x13;
}

class C14 extends C13 {
	int x14;
}

class C15 extends C14 {
	int x15;
}

class C16 extends C15 {
	int x16;
}

class C17 extends C16 {
	int x17;
}

class C18 extends C17 {
	int x18;
}

class C19 extends C18 {
	int x19;
}


void test() {
	C19 c = new C19();
	assert(c.x0 == 0);
	assert(c.x1 == 0);
	assert(c.x2 == 0);
	assert(c.x3 == 0);
	assert(c.x4 == 0);
	assert(c.x5 == 0);
	assert(c.x6 == 0);
	assert(c.x7 == 0);
	assert(c.x8 == 0);
	assert(c.x9 == 0);
	assert(c.x10 == 0);
	assert(c.x11 == 0);
	assert(c.x12 == 0);
	assert(c.x13 == 0);
	assert(c.x14 == 0);
	assert(c.x15 == 0);
	assert(c.x16 == 0);
	assert(c.x17 == 0);
	assert(c.x18 == 0);
	assert(c.x19 == 0);

}

test();
