// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C0 {
	int x0;
	C0() {}
}

class C1 extends C0 {
	int x1;
}

class C2 extends C1 {
	int x2;
}

class C3 extends C2 {
	int x3;
}

class C4 extends C3 {
	int x4;
}

class C5 extends C4 {
	int x5;
}

class C6 extends C5 {
	int x6;
}

class C7 extends C6 {
	int x7;
}

class C8 extends C7 {
	int x8;
}

class C9 extends C8 {
	int x9;
}

class C10 extends C9 {
	int x10;
}

class C11 extends C10 {
	int x11;
}

class C12 extends C11 {
	int x12;
}

class C13 extends C12 {
	int x13;
}

class C14 extends C13 {
	int x14;
}

class C15 extends C14 {
	int x15;
}

class C16 extends C15 {
	int x16;
}

class C17 extends C16 {
	int x17;
}

class C18 extends C17 {
	int x18;
}

class C19 extends C18 {
	int x19;
}

class C20 extends C19 {
	int x20;
}

class C21 extends C20 {
	int x21;
}

class C22 extends C21 {
	int x22;
}

class C23 extends C22 {
	int x23;
}

class C24 extends C23 {
	int x24;
}

class C25 extends C24 {
	int x25;
}

class C26 extends C25 {
	int x26;
}

class C27 extends C26 {
	int x27;
}

class C28 extends C27 {
	int x28;
}

class C29 extends C28 {
	int x29;
}

class C30 extends C29 {
	int x30;
}

class C31 extends C30 {
	int x31;
}

class C32 extends C31 {
	int x32;
}

class C33 extends C32 {
	int x33;
}

class C34 extends C33 {
	int x34;
}

class C35 extends C34 {
	int x35;
}

class C36 extends C35 {
	int x36;
}

class C37 extends C36 {
	int x37;
}

class C38 extends C37 {
	int x38;
}

class C39 extends C38 {
	int x39;
}

class C40 extends C39 {
	int x40;
}

class C41 extends C40 {
	int x41;
}

class C42 extends C41 {
	int x42;
}

class C43 extends C42 {
	int x43;
}

class C44 extends C43 {
	int x44;
}

class C45 extends C44 {
	int x45;
}

class C46 extends C45 {
	int x46;
}

class C47 extends C46 {
	int x47;
}

class C48 extends C47 {
	int x48;
}

class C49 extends C48 {
	int x49;
}

class C50 extends C49 {
	int x50;
}

class C51 extends C50 {
	int x51;
}

class C52 extends C51 {
	int x52;
}

class C53 extends C52 {
	int x53;
}

class C54 extends C53 {
	int x54;
}

class C55 extends C54 {
	int x55;
}

class C56 extends C55 {
	int x56;
}

class C57 extends C56 {
	int x57;
}

class C58 extends C57 {
	int x58;
}

class C59 extends C58 {
	int x59;
}

class C60 extends C59 {
	int x60;
}

class C61 extends C60 {
	int x61;
}

class C62 extends C61 {
	int x62;
}

class C63 extends C62 {
	int x63;
}

class C64 extends C63 {
	int x64;
}

class C65 extends C64 {
	int x65;
}

class C66 extends C65 {
	int x66;
}

class C67 extends C66 {
	int x67;
}

class C68 extends C67 {
	int x68;
}

class C69 extends C68 {
	int x69;
}

class C70 extends C69 {
	int x70;
}

class C71 extends C70 {
	int x71;
}

class C72 extends C71 {
	int x72;
}

class C73 extends C72 {
	int x73;
}

class C74 extends C73 {
	int x74;
}

class C75 extends C74 {
	int x75;
}

class C76 extends C75 {
	int x76;
}

class C77 extends C76 {
	int x77;
}

class C78 extends C77 {
	int x78;
}

class C79 extends C78 {
	int x79;
}

class C80 extends C79 {
	int x80;
}

class C81 extends C80 {
	int x81;
}

class C82 extends C81 {
	int x82;
}

class C83 extends C82 {
	int x83;
}

class C84 extends C83 {
	int x84;
}

class C85 extends C84 {
	int x85;
}

class C86 extends C85 {
	int x86;
}

class C87 extends C86 {
	int x87;
}

class C88 extends C87 {
	int x88;
}

class C89 extends C88 {
	int x89;
}

class C90 extends C89 {
	int x90;
}

class C91 extends C90 {
	int x91;
}

class C92 extends C91 {
	int x92;
}

class C93 extends C92 {
	int x93;
}

class C94 extends C93 {
	int x94;
}

class C95 extends C94 {
	int x95;
}

class C96 extends C95 {
	int x96;
}

class C97 extends C96 {
	int x97;
}

class C98 extends C97 {
	int x98;
}

class C99 extends C98 {
	int x99;
}

class C100 extends C99 {
	int x100;
}

class C101 extends C100 {
	int x101;
}

class C102 extends C101 {
	int x102;
}

class C103 extends C102 {
	int x103;
}

class C104 extends C103 {
	int x104;
}

class C105 extends C104 {
	int x105;
}

class C106 extends C105 {
	int x106;
}

class C107 extends C106 {
	int x107;
}

class C108 extends C107 {
	int x108;
}

class C109 extends C108 {
	int x109;
}

class C110 extends C109 {
	int x110;
}

class C111 extends C110 {
	int x111;
}

class C112 extends C111 {
	int x112;
}

class C113 extends C112 {
	int x113;
}

class C114 extends C113 {
	int x114;
}

class C115 extends C114 {
	int x115;
}

class C116 extends C115 {
	int x116;
}

class C117 extends C116 {
	int x117;
}

class C118 extends C117 {
	int x118;
}

class C119 extends C118 {
	int x119;
}

class C120 extends C119 {
	int x120;
}

class C121 extends C120 {
	int x121;
}

class C122 extends C121 {
	int x122;
}

class C123 extends C122 {
	int x123;
}

class C124 extends C123 {
	int x124;
}

class C125 extends C124 {
	int x125;
}

class C126 extends C125 {
	int x126;
}

class C127 extends C126 {
	int x127;
}

class C128 extends C127 {
	int x128;
}

class C129 extends C128 {
	int x129;
}

class C130 extends C129 {
	int x130;
}

class C131 extends C130 {
	int x131;
}

class C132 extends C131 {
	int x132;
}

class C133 extends C132 {
	int x133;
}

class C134 extends C133 {
	int x134;
}

class C135 extends C134 {
	int x135;
}

class C136 extends C135 {
	int x136;
}

class C137 extends C136 {
	int x137;
}

class C138 extends C137 {
	int x138;
}

class C139 extends C138 {
	int x139;
}

class C140 extends C139 {
	int x140;
}

class C141 extends C140 {
	int x141;
}

class C142 extends C141 {
	int x142;
}

class C143 extends C142 {
	int x143;
}

class C144 extends C143 {
	int x144;
}

class C145 extends C144 {
	int x145;
}

class C146 extends C145 {
	int x146;
}

class C147 extends C146 {
	int x147;
}

class C148 extends C147 {
	int x148;
}

class C149 extends C148 {
	int x149;
}

class C150 extends C149 {
	int x150;
}

class C151 extends C150 {
	int x151;
}

class C152 extends C151 {
	int x152;
}

class C153 extends C152 {
	int x153;
}

class C154 extends C153 {
	int x154;
}

class C155 extends C154 {
	int x155;
}

class C156 extends C155 {
	int x156;
}

class C157 extends C156 {
	int x157;
}

class C158 extends C157 {
	int x158;
}

class C159 extends C158 {
	int x159;
}

class C160 extends C159 {
	int x160;
}

class C161 extends C160 {
	int x161;
}

class C162 extends C161 {
	int x162;
}

class C163 extends C162 {
	int x163;
}

class C164 extends C163 {
	int x164;
}

class C165 extends C164 {
	int x165;
}

class C166 extends C165 {
	int x166;
}

class C167 extends C166 {
	int x167;
}

class C168 extends C167 {
	int x168;
}

class C169 extends C168 {
	int x169;
}

class C170 extends C169 {
	int x170;
}

class C171 extends C170 {
	int x171;
}

class C172 extends C171 {
	int x172;
}

class C173 extends C172 {
	int x173;
}

class C174 extends C173 {
	int x174;
}

class C175 extends C174 {
	int x175;
}

class C176 extends C175 {
	int x176;
}

class C177 extends C176 {
	int x177;
}

class C178 extends C177 {
	int x178;
}

class C179 extends C178 {
	int x179;
}

class C180 extends C179 {
	int x180;
}

class C181 extends C180 {
	int x181;
}

class C182 extends C181 {
	int x182;
}

class C183 extends C182 {
	int x183;
}

class C184 extends C183 {
	int x184;
}

class C185 extends C184 {
	int x185;
}

class C186 extends C185 {
	int x186;
}

class C187 extends C186 {
	int x187;
}

class C188 extends C187 {
	int x188;
}

class C189 extends C188 {
	int x189;
}

class C190 extends C189 {
	int x190;
}

class C191 extends C190 {
	int x191;
}

class C192 extends C191 {
	int x192;
}

class C193 extends C192 {
	int x193;
}

class C194 extends C193 {
	int x194;
}

class C195 extends C194 {
	int x195;
}

class C196 extends C195 {
	int x196;
}

class C197 extends C196 {
	int x197;
}

class C198 extends C197 {
	int x198;
}

class C199 extends C198 {
	int x199;
}


void test() {
	C199 c = new C199();
	assert(c.x0 == 0);
	assert(c.x1 == 0);
	assert(c.x2 == 0);
	assert(c.x3 == 0);
	assert(c.x4 == 0);
	assert(c.x5 == 0);
	assert(c.x6 == 0);
	assert(c.x7 == 0);
	assert(c.x8 == 0);
	assert(c.x9 == 0);
	assert(c.x10 == 0);
	assert(c.x11 == 0);
	assert(c.x12 == 0);
	assert(c.x13 == 0);
	assert(c.x14 == 0);
	assert(c.x15 == 0);
	assert(c.x16 == 0);
	assert(c.x17 == 0);
	assert(c.x18 == 0);
	assert(c.x19 == 0);
	assert(c.x20 == 0);
	assert(c.x21 == 0);
	assert(c.x22 == 0);
	assert(c.x23 == 0);
	assert(c.x24 == 0);
	assert(c.x25 == 0);
	assert(c.x26 == 0);
	assert(c.x27 == 0);
	assert(c.x28 == 0);
	assert(c.x29 == 0);
	assert(c.x30 == 0);
	assert(c.x31 == 0);
	assert(c.x32 == 0);
	assert(c.x33 == 0);
	assert(c.x34 == 0);
	assert(c.x35 == 0);
	assert(c.x36 == 0);
	assert(c.x37 == 0);
	assert(c.x38 == 0);
	assert(c.x39 == 0);
	assert(c.x40 == 0);
	assert(c.x41 == 0);
	assert(c.x42 == 0);
	assert(c.x43 == 0);
	assert(c.x44 == 0);
	assert(c.x45 == 0);
	assert(c.x46 == 0);
	assert(c.x47 == 0);
	assert(c.x48 == 0);
	assert(c.x49 == 0);
	assert(c.x50 == 0);
	assert(c.x51 == 0);
	assert(c.x52 == 0);
	assert(c.x53 == 0);
	assert(c.x54 == 0);
	assert(c.x55 == 0);
	assert(c.x56 == 0);
	assert(c.x57 == 0);
	assert(c.x58 == 0);
	assert(c.x59 == 0);
	assert(c.x60 == 0);
	assert(c.x61 == 0);
	assert(c.x62 == 0);
	assert(c.x63 == 0);
	assert(c.x64 == 0);
	assert(c.x65 == 0);
	assert(c.x66 == 0);
	assert(c.x67 == 0);
	assert(c.x68 == 0);
	assert(c.x69 == 0);
	assert(c.x70 == 0);
	assert(c.x71 == 0);
	assert(c.x72 == 0);
	assert(c.x73 == 0);
	assert(c.x74 == 0);
	assert(c.x75 == 0);
	assert(c.x76 == 0);
	assert(c.x77 == 0);
	assert(c.x78 == 0);
	assert(c.x79 == 0);
	assert(c.x80 == 0);
	assert(c.x81 == 0);
	assert(c.x82 == 0);
	assert(c.x83 == 0);
	assert(c.x84 == 0);
	assert(c.x85 == 0);
	assert(c.x86 == 0);
	assert(c.x87 == 0);
	assert(c.x88 == 0);
	assert(c.x89 == 0);
	assert(c.x90 == 0);
	assert(c.x91 == 0);
	assert(c.x92 == 0);
	assert(c.x93 == 0);
	assert(c.x94 == 0);
	assert(c.x95 == 0);
	assert(c.x96 == 0);
	assert(c.x97 == 0);
	assert(c.x98 == 0);
	assert(c.x99 == 0);
	assert(c.x100 == 0);
	assert(c.x101 == 0);
	assert(c.x102 == 0);
	assert(c.x103 == 0);
	assert(c.x104 == 0);
	assert(c.x105 == 0);
	assert(c.x106 == 0);
	assert(c.x107 == 0);
	assert(c.x108 == 0);
	assert(c.x109 == 0);
	assert(c.x110 == 0);
	assert(c.x111 == 0);
	assert(c.x112 == 0);
	assert(c.x113 == 0);
	assert(c.x114 == 0);
	assert(c.x115 == 0);
	assert(c.x116 == 0);
	assert(c.x117 == 0);
	assert(c.x118 == 0);
	assert(c.x119 == 0);
	assert(c.x120 == 0);
	assert(c.x121 == 0);
	assert(c.x122 == 0);
	assert(c.x123 == 0);
	assert(c.x124 == 0);
	assert(c.x125 == 0);
	assert(c.x126 == 0);
	assert(c.x127 == 0);
	assert(c.x128 == 0);
	assert(c.x129 == 0);
	assert(c.x130 == 0);
	assert(c.x131 == 0);
	assert(c.x132 == 0);
	assert(c.x133 == 0);
	assert(c.x134 == 0);
	assert(c.x135 == 0);
	assert(c.x136 == 0);
	assert(c.x137 == 0);
	assert(c.x138 == 0);
	assert(c.x139 == 0);
	assert(c.x140 == 0);
	assert(c.x141 == 0);
	assert(c.x142 == 0);
	assert(c.x143 == 0);
	assert(c.x144 == 0);
	assert(c.x145 == 0);
	assert(c.x146 == 0);
	assert(c.x147 == 0);
	assert(c.x148 == 0);
	assert(c.x149 == 0);
	assert(c.x150 == 0);
	assert(c.x151 == 0);
	assert(c.x152 == 0);
	assert(c.x153 == 0);
	assert(c.x154 == 0);
	assert(c.x155 == 0);
	assert(c.x156 == 0);
	assert(c.x157 == 0);
	assert(c.x158 == 0);
	assert(c.x159 == 0);
	assert(c.x160 == 0);
	assert(c.x161 == 0);
	assert(c.x162 == 0);
	assert(c.x163 == 0);
	assert(c.x164 == 0);
	assert(c.x165 == 0);
	assert(c.x166 == 0);
	assert(c.x167 == 0);
	assert(c.x168 == 0);
	assert(c.x169 == 0);
	assert(c.x170 == 0);
	assert(c.x171 == 0);
	assert(c.x172 == 0);
	assert(c.x173 == 0);
	assert(c.x174 == 0);
	assert(c.x175 == 0);
	assert(c.x176 == 0);
	assert(c.x177 == 0);
	assert(c.x178 == 0);
	assert(c.x179 == 0);
	assert(c.x180 == 0);
	assert(c.x181 == 0);
	assert(c.x182 == 0);
	assert(c.x183 == 0);
	assert(c.x184 == 0);
	assert(c.x185 == 0);
	assert(c.x186 == 0);
	assert(c.x187 == 0);
	assert(c.x188 == 0);
	assert(c.x189 == 0);
	assert(c.x190 == 0);
	assert(c.x191 == 0);
	assert(c.x192 == 0);
	assert(c.x193 == 0);
	assert(c.x194 == 0);
	assert(c.x195 == 0);
	assert(c.x196 == 0);
	assert(c.x197 == 0);
	assert(c.x198 == 0);
	assert(c.x199 == 0);

}

test();
