// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C0 {int x0; }
class C1 {int x1; }
class C2 {int x2; }
class C3 {int x3; }
class C4 {int x4; }
class C5 {int x5; }
class C6 {int x6; }
class C7 {int x7; }
class C8 {int x8; }
class C9 {int x9; }
class C10 {int x10; }
class C11 {int x11; }
class C12 {int x12; }
class C13 {int x13; }
class C14 {int x14; }
class C15 {int x15; }
class C16 {int x16; }
class C17 {int x17; }
class C18 {int x18; }
class C19 {int x19; }
class C20 {int x20; }
class C21 {int x21; }
class C22 {int x22; }
class C23 {int x23; }
class C24 {int x24; }
class C25 {int x25; }
class C26 {int x26; }
class C27 {int x27; }
class C28 {int x28; }
class C29 {int x29; }
class C30 {int x30; }
class C31 {int x31; }
class C32 {int x32; }
class C33 {int x33; }
class C34 {int x34; }
class C35 {int x35; }
class C36 {int x36; }
class C37 {int x37; }
class C38 {int x38; }
class C39 {int x39; }
class C40 {int x40; }
class C41 {int x41; }
class C42 {int x42; }
class C43 {int x43; }
class C44 {int x44; }
class C45 {int x45; }
class C46 {int x46; }
class C47 {int x47; }
class C48 {int x48; }
class C49 {int x49; }
class C50 {int x50; }
class C51 {int x51; }
class C52 {int x52; }
class C53 {int x53; }
class C54 {int x54; }
class C55 {int x55; }
class C56 {int x56; }
class C57 {int x57; }
class C58 {int x58; }
class C59 {int x59; }
class C60 {int x60; }
class C61 {int x61; }
class C62 {int x62; }
class C63 {int x63; }
class C64 {int x64; }
class C65 {int x65; }
class C66 {int x66; }
class C67 {int x67; }
class C68 {int x68; }
class C69 {int x69; }
class C70 {int x70; }
class C71 {int x71; }
class C72 {int x72; }
class C73 {int x73; }
class C74 {int x74; }
class C75 {int x75; }
class C76 {int x76; }
class C77 {int x77; }
class C78 {int x78; }
class C79 {int x79; }
class C80 {int x80; }
class C81 {int x81; }
class C82 {int x82; }
class C83 {int x83; }
class C84 {int x84; }
class C85 {int x85; }
class C86 {int x86; }
class C87 {int x87; }
class C88 {int x88; }
class C89 {int x89; }
class C90 {int x90; }
class C91 {int x91; }
class C92 {int x92; }
class C93 {int x93; }
class C94 {int x94; }
class C95 {int x95; }
class C96 {int x96; }
class C97 {int x97; }
class C98 {int x98; }
class C99 {int x99; }

C0;
C1;
C2;
C3;
C4;
C5;
C6;
C7;
C8;
C9;
C10;
C11;
C12;
C13;
C14;
C15;
C16;
C17;
C18;
C19;
C20;
C21;
C22;
C23;
C24;
C25;
C26;
C27;
C28;
C29;
C30;
C31;
C32;
C33;
C34;
C35;
C36;
C37;
C38;
C39;
C40;
C41;
C42;
C43;
C44;
C45;
C46;
C47;
C48;
C49;
C50;
C51;
C52;
C53;
C54;
C55;
C56;
C57;
C58;
C59;
C60;
C61;
C62;
C63;
C64;
C65;
C66;
C67;
C68;
C69;
C70;
C71;
C72;
C73;
C74;
C75;
C76;
C77;
C78;
C79;
C80;
C81;
C82;
C83;
C84;
C85;
C86;
C87;
C88;
C89;
C90;
C91;
C92;
C93;
C94;
C95;
C96;
C97;
C98;
C99;

