// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C0 {
	int x0;
	C0() {}
}

class C1 extends C0 {
	int x1;
}

class C2 extends C1 {
	int x2;
}

class C3 extends C2 {
	int x3;
}

class C4 extends C3 {
	int x4;
}

class C5 extends C4 {
	int x5;
}

class C6 extends C5 {
	int x6;
}

class C7 extends C6 {
	int x7;
}

class C8 extends C7 {
	int x8;
}

class C9 extends C8 {
	int x9;
}

class C10 extends C9 {
	int x10;
}

class C11 extends C10 {
	int x11;
}

class C12 extends C11 {
	int x12;
}

class C13 extends C12 {
	int x13;
}

class C14 extends C13 {
	int x14;
}

class C15 extends C14 {
	int x15;
}

class C16 extends C15 {
	int x16;
}

class C17 extends C16 {
	int x17;
}

class C18 extends C17 {
	int x18;
}

class C19 extends C18 {
	int x19;
}

class C20 extends C19 {
	int x20;
}

class C21 extends C20 {
	int x21;
}

class C22 extends C21 {
	int x22;
}

class C23 extends C22 {
	int x23;
}

class C24 extends C23 {
	int x24;
}

class C25 extends C24 {
	int x25;
}

class C26 extends C25 {
	int x26;
}

class C27 extends C26 {
	int x27;
}

class C28 extends C27 {
	int x28;
}

class C29 extends C28 {
	int x29;
}

class C30 extends C29 {
	int x30;
}

class C31 extends C30 {
	int x31;
}

class C32 extends C31 {
	int x32;
}

class C33 extends C32 {
	int x33;
}

class C34 extends C33 {
	int x34;
}

class C35 extends C34 {
	int x35;
}

class C36 extends C35 {
	int x36;
}

class C37 extends C36 {
	int x37;
}

class C38 extends C37 {
	int x38;
}

class C39 extends C38 {
	int x39;
}

class C40 extends C39 {
	int x40;
}

class C41 extends C40 {
	int x41;
}

class C42 extends C41 {
	int x42;
}

class C43 extends C42 {
	int x43;
}

class C44 extends C43 {
	int x44;
}

class C45 extends C44 {
	int x45;
}

class C46 extends C45 {
	int x46;
}

class C47 extends C46 {
	int x47;
}

class C48 extends C47 {
	int x48;
}

class C49 extends C48 {
	int x49;
}


void test() {
	C49 c = new C49();
	assert(c.x0 == 0);
	assert(c.x1 == 0);
	assert(c.x2 == 0);
	assert(c.x3 == 0);
	assert(c.x4 == 0);
	assert(c.x5 == 0);
	assert(c.x6 == 0);
	assert(c.x7 == 0);
	assert(c.x8 == 0);
	assert(c.x9 == 0);
	assert(c.x10 == 0);
	assert(c.x11 == 0);
	assert(c.x12 == 0);
	assert(c.x13 == 0);
	assert(c.x14 == 0);
	assert(c.x15 == 0);
	assert(c.x16 == 0);
	assert(c.x17 == 0);
	assert(c.x18 == 0);
	assert(c.x19 == 0);
	assert(c.x20 == 0);
	assert(c.x21 == 0);
	assert(c.x22 == 0);
	assert(c.x23 == 0);
	assert(c.x24 == 0);
	assert(c.x25 == 0);
	assert(c.x26 == 0);
	assert(c.x27 == 0);
	assert(c.x28 == 0);
	assert(c.x29 == 0);
	assert(c.x30 == 0);
	assert(c.x31 == 0);
	assert(c.x32 == 0);
	assert(c.x33 == 0);
	assert(c.x34 == 0);
	assert(c.x35 == 0);
	assert(c.x36 == 0);
	assert(c.x37 == 0);
	assert(c.x38 == 0);
	assert(c.x39 == 0);
	assert(c.x40 == 0);
	assert(c.x41 == 0);
	assert(c.x42 == 0);
	assert(c.x43 == 0);
	assert(c.x44 == 0);
	assert(c.x45 == 0);
	assert(c.x46 == 0);
	assert(c.x47 == 0);
	assert(c.x48 == 0);
	assert(c.x49 == 0);

}

test();
