// written by kimio kuramitsu

import("Syntax.JavaStyleClass");

class C0 {
	int x0;
	C0() {}
}

class C1 extends C0 {
	int x1;
}

class C2 extends C1 {
	int x2;
}

class C3 extends C2 {
	int x3;
}

class C4 extends C3 {
	int x4;
}

class C5 extends C4 {
	int x5;
}

class C6 extends C5 {
	int x6;
}

class C7 extends C6 {
	int x7;
}

class C8 extends C7 {
	int x8;
}

class C9 extends C8 {
	int x9;
}

class C10 extends C9 {
	int x10;
}

class C11 extends C10 {
	int x11;
}

class C12 extends C11 {
	int x12;
}

class C13 extends C12 {
	int x13;
}

class C14 extends C13 {
	int x14;
}

class C15 extends C14 {
	int x15;
}

class C16 extends C15 {
	int x16;
}

class C17 extends C16 {
	int x17;
}

class C18 extends C17 {
	int x18;
}

class C19 extends C18 {
	int x19;
}

class C20 extends C19 {
	int x20;
}

class C21 extends C20 {
	int x21;
}

class C22 extends C21 {
	int x22;
}

class C23 extends C22 {
	int x23;
}

class C24 extends C23 {
	int x24;
}

class C25 extends C24 {
	int x25;
}

class C26 extends C25 {
	int x26;
}

class C27 extends C26 {
	int x27;
}

class C28 extends C27 {
	int x28;
}

class C29 extends C28 {
	int x29;
}

class C30 extends C29 {
	int x30;
}

class C31 extends C30 {
	int x31;
}

class C32 extends C31 {
	int x32;
}

class C33 extends C32 {
	int x33;
}

class C34 extends C33 {
	int x34;
}

class C35 extends C34 {
	int x35;
}

class C36 extends C35 {
	int x36;
}

class C37 extends C36 {
	int x37;
}

class C38 extends C37 {
	int x38;
}

class C39 extends C38 {
	int x39;
}

class C40 extends C39 {
	int x40;
}

class C41 extends C40 {
	int x41;
}

class C42 extends C41 {
	int x42;
}

class C43 extends C42 {
	int x43;
}

class C44 extends C43 {
	int x44;
}

class C45 extends C44 {
	int x45;
}

class C46 extends C45 {
	int x46;
}

class C47 extends C46 {
	int x47;
}

class C48 extends C47 {
	int x48;
}

class C49 extends C48 {
	int x49;
}

class C50 extends C49 {
	int x50;
}

class C51 extends C50 {
	int x51;
}

class C52 extends C51 {
	int x52;
}

class C53 extends C52 {
	int x53;
}

class C54 extends C53 {
	int x54;
}

class C55 extends C54 {
	int x55;
}

class C56 extends C55 {
	int x56;
}

class C57 extends C56 {
	int x57;
}

class C58 extends C57 {
	int x58;
}

class C59 extends C58 {
	int x59;
}

class C60 extends C59 {
	int x60;
}

class C61 extends C60 {
	int x61;
}

class C62 extends C61 {
	int x62;
}

class C63 extends C62 {
	int x63;
}

class C64 extends C63 {
	int x64;
}

class C65 extends C64 {
	int x65;
}

class C66 extends C65 {
	int x66;
}

class C67 extends C66 {
	int x67;
}

class C68 extends C67 {
	int x68;
}

class C69 extends C68 {
	int x69;
}

class C70 extends C69 {
	int x70;
}

class C71 extends C70 {
	int x71;
}

class C72 extends C71 {
	int x72;
}

class C73 extends C72 {
	int x73;
}

class C74 extends C73 {
	int x74;
}

class C75 extends C74 {
	int x75;
}

class C76 extends C75 {
	int x76;
}

class C77 extends C76 {
	int x77;
}

class C78 extends C77 {
	int x78;
}

class C79 extends C78 {
	int x79;
}

class C80 extends C79 {
	int x80;
}

class C81 extends C80 {
	int x81;
}

class C82 extends C81 {
	int x82;
}

class C83 extends C82 {
	int x83;
}

class C84 extends C83 {
	int x84;
}

class C85 extends C84 {
	int x85;
}

class C86 extends C85 {
	int x86;
}

class C87 extends C86 {
	int x87;
}

class C88 extends C87 {
	int x88;
}

class C89 extends C88 {
	int x89;
}

class C90 extends C89 {
	int x90;
}

class C91 extends C90 {
	int x91;
}

class C92 extends C91 {
	int x92;
}

class C93 extends C92 {
	int x93;
}

class C94 extends C93 {
	int x94;
}

class C95 extends C94 {
	int x95;
}

class C96 extends C95 {
	int x96;
}

class C97 extends C96 {
	int x97;
}

class C98 extends C97 {
	int x98;
}

class C99 extends C98 {
	int x99;
}

class C100 extends C99 {
	int x100;
}

class C101 extends C100 {
	int x101;
}

class C102 extends C101 {
	int x102;
}

class C103 extends C102 {
	int x103;
}

class C104 extends C103 {
	int x104;
}

class C105 extends C104 {
	int x105;
}

class C106 extends C105 {
	int x106;
}

class C107 extends C106 {
	int x107;
}

class C108 extends C107 {
	int x108;
}

class C109 extends C108 {
	int x109;
}

class C110 extends C109 {
	int x110;
}

class C111 extends C110 {
	int x111;
}

class C112 extends C111 {
	int x112;
}

class C113 extends C112 {
	int x113;
}

class C114 extends C113 {
	int x114;
}

class C115 extends C114 {
	int x115;
}

class C116 extends C115 {
	int x116;
}

class C117 extends C116 {
	int x117;
}

class C118 extends C117 {
	int x118;
}

class C119 extends C118 {
	int x119;
}

class C120 extends C119 {
	int x120;
}

class C121 extends C120 {
	int x121;
}

class C122 extends C121 {
	int x122;
}

class C123 extends C122 {
	int x123;
}

class C124 extends C123 {
	int x124;
}

class C125 extends C124 {
	int x125;
}

class C126 extends C125 {
	int x126;
}

class C127 extends C126 {
	int x127;
}

class C128 extends C127 {
	int x128;
}

class C129 extends C128 {
	int x129;
}

class C130 extends C129 {
	int x130;
}

class C131 extends C130 {
	int x131;
}

class C132 extends C131 {
	int x132;
}

class C133 extends C132 {
	int x133;
}

class C134 extends C133 {
	int x134;
}

class C135 extends C134 {
	int x135;
}

class C136 extends C135 {
	int x136;
}

class C137 extends C136 {
	int x137;
}

class C138 extends C137 {
	int x138;
}

class C139 extends C138 {
	int x139;
}

class C140 extends C139 {
	int x140;
}

class C141 extends C140 {
	int x141;
}

class C142 extends C141 {
	int x142;
}

class C143 extends C142 {
	int x143;
}

class C144 extends C143 {
	int x144;
}

class C145 extends C144 {
	int x145;
}

class C146 extends C145 {
	int x146;
}

class C147 extends C146 {
	int x147;
}

class C148 extends C147 {
	int x148;
}

class C149 extends C148 {
	int x149;
}

class C150 extends C149 {
	int x150;
}

class C151 extends C150 {
	int x151;
}

class C152 extends C151 {
	int x152;
}

class C153 extends C152 {
	int x153;
}

class C154 extends C153 {
	int x154;
}

class C155 extends C154 {
	int x155;
}

class C156 extends C155 {
	int x156;
}

class C157 extends C156 {
	int x157;
}

class C158 extends C157 {
	int x158;
}

class C159 extends C158 {
	int x159;
}

class C160 extends C159 {
	int x160;
}

class C161 extends C160 {
	int x161;
}

class C162 extends C161 {
	int x162;
}

class C163 extends C162 {
	int x163;
}

class C164 extends C163 {
	int x164;
}

class C165 extends C164 {
	int x165;
}

class C166 extends C165 {
	int x166;
}

class C167 extends C166 {
	int x167;
}

class C168 extends C167 {
	int x168;
}

class C169 extends C168 {
	int x169;
}

class C170 extends C169 {
	int x170;
}

class C171 extends C170 {
	int x171;
}

class C172 extends C171 {
	int x172;
}

class C173 extends C172 {
	int x173;
}

class C174 extends C173 {
	int x174;
}

class C175 extends C174 {
	int x175;
}

class C176 extends C175 {
	int x176;
}

class C177 extends C176 {
	int x177;
}

class C178 extends C177 {
	int x178;
}

class C179 extends C178 {
	int x179;
}

class C180 extends C179 {
	int x180;
}

class C181 extends C180 {
	int x181;
}

class C182 extends C181 {
	int x182;
}

class C183 extends C182 {
	int x183;
}

class C184 extends C183 {
	int x184;
}

class C185 extends C184 {
	int x185;
}

class C186 extends C185 {
	int x186;
}

class C187 extends C186 {
	int x187;
}

class C188 extends C187 {
	int x188;
}

class C189 extends C188 {
	int x189;
}

class C190 extends C189 {
	int x190;
}

class C191 extends C190 {
	int x191;
}

class C192 extends C191 {
	int x192;
}

class C193 extends C192 {
	int x193;
}

class C194 extends C193 {
	int x194;
}

class C195 extends C194 {
	int x195;
}

class C196 extends C195 {
	int x196;
}

class C197 extends C196 {
	int x197;
}

class C198 extends C197 {
	int x198;
}

class C199 extends C198 {
	int x199;
}

class C200 extends C199 {
	int x200;
}

class C201 extends C200 {
	int x201;
}

class C202 extends C201 {
	int x202;
}

class C203 extends C202 {
	int x203;
}

class C204 extends C203 {
	int x204;
}

class C205 extends C204 {
	int x205;
}

class C206 extends C205 {
	int x206;
}

class C207 extends C206 {
	int x207;
}

class C208 extends C207 {
	int x208;
}

class C209 extends C208 {
	int x209;
}

class C210 extends C209 {
	int x210;
}

class C211 extends C210 {
	int x211;
}

class C212 extends C211 {
	int x212;
}

class C213 extends C212 {
	int x213;
}

class C214 extends C213 {
	int x214;
}

class C215 extends C214 {
	int x215;
}

class C216 extends C215 {
	int x216;
}

class C217 extends C216 {
	int x217;
}

class C218 extends C217 {
	int x218;
}

class C219 extends C218 {
	int x219;
}

class C220 extends C219 {
	int x220;
}

class C221 extends C220 {
	int x221;
}

class C222 extends C221 {
	int x222;
}

class C223 extends C222 {
	int x223;
}

class C224 extends C223 {
	int x224;
}

class C225 extends C224 {
	int x225;
}

class C226 extends C225 {
	int x226;
}

class C227 extends C226 {
	int x227;
}

class C228 extends C227 {
	int x228;
}

class C229 extends C228 {
	int x229;
}

class C230 extends C229 {
	int x230;
}

class C231 extends C230 {
	int x231;
}

class C232 extends C231 {
	int x232;
}

class C233 extends C232 {
	int x233;
}

class C234 extends C233 {
	int x234;
}

class C235 extends C234 {
	int x235;
}

class C236 extends C235 {
	int x236;
}

class C237 extends C236 {
	int x237;
}

class C238 extends C237 {
	int x238;
}

class C239 extends C238 {
	int x239;
}

class C240 extends C239 {
	int x240;
}

class C241 extends C240 {
	int x241;
}

class C242 extends C241 {
	int x242;
}

class C243 extends C242 {
	int x243;
}

class C244 extends C243 {
	int x244;
}

class C245 extends C244 {
	int x245;
}

class C246 extends C245 {
	int x246;
}

class C247 extends C246 {
	int x247;
}

class C248 extends C247 {
	int x248;
}

class C249 extends C248 {
	int x249;
}

class C250 extends C249 {
	int x250;
}

class C251 extends C250 {
	int x251;
}

class C252 extends C251 {
	int x252;
}

class C253 extends C252 {
	int x253;
}

class C254 extends C253 {
	int x254;
}

class C255 extends C254 {
	int x255;
}

class C256 extends C255 {
	int x256;
}

class C257 extends C256 {
	int x257;
}

class C258 extends C257 {
	int x258;
}

class C259 extends C258 {
	int x259;
}

class C260 extends C259 {
	int x260;
}

class C261 extends C260 {
	int x261;
}

class C262 extends C261 {
	int x262;
}

class C263 extends C262 {
	int x263;
}

class C264 extends C263 {
	int x264;
}

class C265 extends C264 {
	int x265;
}

class C266 extends C265 {
	int x266;
}

class C267 extends C266 {
	int x267;
}

class C268 extends C267 {
	int x268;
}

class C269 extends C268 {
	int x269;
}

class C270 extends C269 {
	int x270;
}

class C271 extends C270 {
	int x271;
}

class C272 extends C271 {
	int x272;
}

class C273 extends C272 {
	int x273;
}

class C274 extends C273 {
	int x274;
}

class C275 extends C274 {
	int x275;
}

class C276 extends C275 {
	int x276;
}

class C277 extends C276 {
	int x277;
}

class C278 extends C277 {
	int x278;
}

class C279 extends C278 {
	int x279;
}

class C280 extends C279 {
	int x280;
}

class C281 extends C280 {
	int x281;
}

class C282 extends C281 {
	int x282;
}

class C283 extends C282 {
	int x283;
}

class C284 extends C283 {
	int x284;
}

class C285 extends C284 {
	int x285;
}

class C286 extends C285 {
	int x286;
}

class C287 extends C286 {
	int x287;
}

class C288 extends C287 {
	int x288;
}

class C289 extends C288 {
	int x289;
}

class C290 extends C289 {
	int x290;
}

class C291 extends C290 {
	int x291;
}

class C292 extends C291 {
	int x292;
}

class C293 extends C292 {
	int x293;
}

class C294 extends C293 {
	int x294;
}

class C295 extends C294 {
	int x295;
}

class C296 extends C295 {
	int x296;
}

class C297 extends C296 {
	int x297;
}

class C298 extends C297 {
	int x298;
}

class C299 extends C298 {
	int x299;
}

class C300 extends C299 {
	int x300;
}

class C301 extends C300 {
	int x301;
}

class C302 extends C301 {
	int x302;
}

class C303 extends C302 {
	int x303;
}

class C304 extends C303 {
	int x304;
}

class C305 extends C304 {
	int x305;
}

class C306 extends C305 {
	int x306;
}

class C307 extends C306 {
	int x307;
}

class C308 extends C307 {
	int x308;
}

class C309 extends C308 {
	int x309;
}

class C310 extends C309 {
	int x310;
}

class C311 extends C310 {
	int x311;
}

class C312 extends C311 {
	int x312;
}

class C313 extends C312 {
	int x313;
}

class C314 extends C313 {
	int x314;
}

class C315 extends C314 {
	int x315;
}

class C316 extends C315 {
	int x316;
}

class C317 extends C316 {
	int x317;
}

class C318 extends C317 {
	int x318;
}

class C319 extends C318 {
	int x319;
}

class C320 extends C319 {
	int x320;
}

class C321 extends C320 {
	int x321;
}

class C322 extends C321 {
	int x322;
}

class C323 extends C322 {
	int x323;
}

class C324 extends C323 {
	int x324;
}

class C325 extends C324 {
	int x325;
}

class C326 extends C325 {
	int x326;
}

class C327 extends C326 {
	int x327;
}

class C328 extends C327 {
	int x328;
}

class C329 extends C328 {
	int x329;
}

class C330 extends C329 {
	int x330;
}

class C331 extends C330 {
	int x331;
}

class C332 extends C331 {
	int x332;
}

class C333 extends C332 {
	int x333;
}

class C334 extends C333 {
	int x334;
}

class C335 extends C334 {
	int x335;
}

class C336 extends C335 {
	int x336;
}

class C337 extends C336 {
	int x337;
}

class C338 extends C337 {
	int x338;
}

class C339 extends C338 {
	int x339;
}

class C340 extends C339 {
	int x340;
}

class C341 extends C340 {
	int x341;
}

class C342 extends C341 {
	int x342;
}

class C343 extends C342 {
	int x343;
}

class C344 extends C343 {
	int x344;
}

class C345 extends C344 {
	int x345;
}

class C346 extends C345 {
	int x346;
}

class C347 extends C346 {
	int x347;
}

class C348 extends C347 {
	int x348;
}

class C349 extends C348 {
	int x349;
}

class C350 extends C349 {
	int x350;
}

class C351 extends C350 {
	int x351;
}

class C352 extends C351 {
	int x352;
}

class C353 extends C352 {
	int x353;
}

class C354 extends C353 {
	int x354;
}

class C355 extends C354 {
	int x355;
}

class C356 extends C355 {
	int x356;
}

class C357 extends C356 {
	int x357;
}

class C358 extends C357 {
	int x358;
}

class C359 extends C358 {
	int x359;
}

class C360 extends C359 {
	int x360;
}

class C361 extends C360 {
	int x361;
}

class C362 extends C361 {
	int x362;
}

class C363 extends C362 {
	int x363;
}

class C364 extends C363 {
	int x364;
}

class C365 extends C364 {
	int x365;
}

class C366 extends C365 {
	int x366;
}

class C367 extends C366 {
	int x367;
}

class C368 extends C367 {
	int x368;
}

class C369 extends C368 {
	int x369;
}

class C370 extends C369 {
	int x370;
}

class C371 extends C370 {
	int x371;
}

class C372 extends C371 {
	int x372;
}

class C373 extends C372 {
	int x373;
}

class C374 extends C373 {
	int x374;
}

class C375 extends C374 {
	int x375;
}

class C376 extends C375 {
	int x376;
}

class C377 extends C376 {
	int x377;
}

class C378 extends C377 {
	int x378;
}

class C379 extends C378 {
	int x379;
}

class C380 extends C379 {
	int x380;
}

class C381 extends C380 {
	int x381;
}

class C382 extends C381 {
	int x382;
}

class C383 extends C382 {
	int x383;
}

class C384 extends C383 {
	int x384;
}

class C385 extends C384 {
	int x385;
}

class C386 extends C385 {
	int x386;
}

class C387 extends C386 {
	int x387;
}

class C388 extends C387 {
	int x388;
}

class C389 extends C388 {
	int x389;
}

class C390 extends C389 {
	int x390;
}

class C391 extends C390 {
	int x391;
}

class C392 extends C391 {
	int x392;
}

class C393 extends C392 {
	int x393;
}

class C394 extends C393 {
	int x394;
}

class C395 extends C394 {
	int x395;
}

class C396 extends C395 {
	int x396;
}

class C397 extends C396 {
	int x397;
}

class C398 extends C397 {
	int x398;
}

class C399 extends C398 {
	int x399;
}

class C400 extends C399 {
	int x400;
}

class C401 extends C400 {
	int x401;
}

class C402 extends C401 {
	int x402;
}

class C403 extends C402 {
	int x403;
}

class C404 extends C403 {
	int x404;
}

class C405 extends C404 {
	int x405;
}

class C406 extends C405 {
	int x406;
}

class C407 extends C406 {
	int x407;
}

class C408 extends C407 {
	int x408;
}

class C409 extends C408 {
	int x409;
}

class C410 extends C409 {
	int x410;
}

class C411 extends C410 {
	int x411;
}

class C412 extends C411 {
	int x412;
}

class C413 extends C412 {
	int x413;
}

class C414 extends C413 {
	int x414;
}

class C415 extends C414 {
	int x415;
}

class C416 extends C415 {
	int x416;
}

class C417 extends C416 {
	int x417;
}

class C418 extends C417 {
	int x418;
}

class C419 extends C418 {
	int x419;
}

class C420 extends C419 {
	int x420;
}

class C421 extends C420 {
	int x421;
}

class C422 extends C421 {
	int x422;
}

class C423 extends C422 {
	int x423;
}

class C424 extends C423 {
	int x424;
}

class C425 extends C424 {
	int x425;
}

class C426 extends C425 {
	int x426;
}

class C427 extends C426 {
	int x427;
}

class C428 extends C427 {
	int x428;
}

class C429 extends C428 {
	int x429;
}

class C430 extends C429 {
	int x430;
}

class C431 extends C430 {
	int x431;
}

class C432 extends C431 {
	int x432;
}

class C433 extends C432 {
	int x433;
}

class C434 extends C433 {
	int x434;
}

class C435 extends C434 {
	int x435;
}

class C436 extends C435 {
	int x436;
}

class C437 extends C436 {
	int x437;
}

class C438 extends C437 {
	int x438;
}

class C439 extends C438 {
	int x439;
}

class C440 extends C439 {
	int x440;
}

class C441 extends C440 {
	int x441;
}

class C442 extends C441 {
	int x442;
}

class C443 extends C442 {
	int x443;
}

class C444 extends C443 {
	int x444;
}

class C445 extends C444 {
	int x445;
}

class C446 extends C445 {
	int x446;
}

class C447 extends C446 {
	int x447;
}

class C448 extends C447 {
	int x448;
}

class C449 extends C448 {
	int x449;
}

class C450 extends C449 {
	int x450;
}

class C451 extends C450 {
	int x451;
}

class C452 extends C451 {
	int x452;
}

class C453 extends C452 {
	int x453;
}

class C454 extends C453 {
	int x454;
}

class C455 extends C454 {
	int x455;
}

class C456 extends C455 {
	int x456;
}

class C457 extends C456 {
	int x457;
}

class C458 extends C457 {
	int x458;
}

class C459 extends C458 {
	int x459;
}

class C460 extends C459 {
	int x460;
}

class C461 extends C460 {
	int x461;
}

class C462 extends C461 {
	int x462;
}

class C463 extends C462 {
	int x463;
}

class C464 extends C463 {
	int x464;
}

class C465 extends C464 {
	int x465;
}

class C466 extends C465 {
	int x466;
}

class C467 extends C466 {
	int x467;
}

class C468 extends C467 {
	int x468;
}

class C469 extends C468 {
	int x469;
}

class C470 extends C469 {
	int x470;
}

class C471 extends C470 {
	int x471;
}

class C472 extends C471 {
	int x472;
}

class C473 extends C472 {
	int x473;
}

class C474 extends C473 {
	int x474;
}

class C475 extends C474 {
	int x475;
}

class C476 extends C475 {
	int x476;
}

class C477 extends C476 {
	int x477;
}

class C478 extends C477 {
	int x478;
}

class C479 extends C478 {
	int x479;
}

class C480 extends C479 {
	int x480;
}

class C481 extends C480 {
	int x481;
}

class C482 extends C481 {
	int x482;
}

class C483 extends C482 {
	int x483;
}

class C484 extends C483 {
	int x484;
}

class C485 extends C484 {
	int x485;
}

class C486 extends C485 {
	int x486;
}

class C487 extends C486 {
	int x487;
}

class C488 extends C487 {
	int x488;
}

class C489 extends C488 {
	int x489;
}

class C490 extends C489 {
	int x490;
}

class C491 extends C490 {
	int x491;
}

class C492 extends C491 {
	int x492;
}

class C493 extends C492 {
	int x493;
}

class C494 extends C493 {
	int x494;
}

class C495 extends C494 {
	int x495;
}

class C496 extends C495 {
	int x496;
}

class C497 extends C496 {
	int x497;
}

class C498 extends C497 {
	int x498;
}

class C499 extends C498 {
	int x499;
}


void test() {
	C499 c = new C499();
	assert(c.x0 == 0);
	assert(c.x1 == 0);
	assert(c.x2 == 0);
	assert(c.x3 == 0);
	assert(c.x4 == 0);
	assert(c.x5 == 0);
	assert(c.x6 == 0);
	assert(c.x7 == 0);
	assert(c.x8 == 0);
	assert(c.x9 == 0);
	assert(c.x10 == 0);
	assert(c.x11 == 0);
	assert(c.x12 == 0);
	assert(c.x13 == 0);
	assert(c.x14 == 0);
	assert(c.x15 == 0);
	assert(c.x16 == 0);
	assert(c.x17 == 0);
	assert(c.x18 == 0);
	assert(c.x19 == 0);
	assert(c.x20 == 0);
	assert(c.x21 == 0);
	assert(c.x22 == 0);
	assert(c.x23 == 0);
	assert(c.x24 == 0);
	assert(c.x25 == 0);
	assert(c.x26 == 0);
	assert(c.x27 == 0);
	assert(c.x28 == 0);
	assert(c.x29 == 0);
	assert(c.x30 == 0);
	assert(c.x31 == 0);
	assert(c.x32 == 0);
	assert(c.x33 == 0);
	assert(c.x34 == 0);
	assert(c.x35 == 0);
	assert(c.x36 == 0);
	assert(c.x37 == 0);
	assert(c.x38 == 0);
	assert(c.x39 == 0);
	assert(c.x40 == 0);
	assert(c.x41 == 0);
	assert(c.x42 == 0);
	assert(c.x43 == 0);
	assert(c.x44 == 0);
	assert(c.x45 == 0);
	assert(c.x46 == 0);
	assert(c.x47 == 0);
	assert(c.x48 == 0);
	assert(c.x49 == 0);
	assert(c.x50 == 0);
	assert(c.x51 == 0);
	assert(c.x52 == 0);
	assert(c.x53 == 0);
	assert(c.x54 == 0);
	assert(c.x55 == 0);
	assert(c.x56 == 0);
	assert(c.x57 == 0);
	assert(c.x58 == 0);
	assert(c.x59 == 0);
	assert(c.x60 == 0);
	assert(c.x61 == 0);
	assert(c.x62 == 0);
	assert(c.x63 == 0);
	assert(c.x64 == 0);
	assert(c.x65 == 0);
	assert(c.x66 == 0);
	assert(c.x67 == 0);
	assert(c.x68 == 0);
	assert(c.x69 == 0);
	assert(c.x70 == 0);
	assert(c.x71 == 0);
	assert(c.x72 == 0);
	assert(c.x73 == 0);
	assert(c.x74 == 0);
	assert(c.x75 == 0);
	assert(c.x76 == 0);
	assert(c.x77 == 0);
	assert(c.x78 == 0);
	assert(c.x79 == 0);
	assert(c.x80 == 0);
	assert(c.x81 == 0);
	assert(c.x82 == 0);
	assert(c.x83 == 0);
	assert(c.x84 == 0);
	assert(c.x85 == 0);
	assert(c.x86 == 0);
	assert(c.x87 == 0);
	assert(c.x88 == 0);
	assert(c.x89 == 0);
	assert(c.x90 == 0);
	assert(c.x91 == 0);
	assert(c.x92 == 0);
	assert(c.x93 == 0);
	assert(c.x94 == 0);
	assert(c.x95 == 0);
	assert(c.x96 == 0);
	assert(c.x97 == 0);
	assert(c.x98 == 0);
	assert(c.x99 == 0);
	assert(c.x100 == 0);
	assert(c.x101 == 0);
	assert(c.x102 == 0);
	assert(c.x103 == 0);
	assert(c.x104 == 0);
	assert(c.x105 == 0);
	assert(c.x106 == 0);
	assert(c.x107 == 0);
	assert(c.x108 == 0);
	assert(c.x109 == 0);
	assert(c.x110 == 0);
	assert(c.x111 == 0);
	assert(c.x112 == 0);
	assert(c.x113 == 0);
	assert(c.x114 == 0);
	assert(c.x115 == 0);
	assert(c.x116 == 0);
	assert(c.x117 == 0);
	assert(c.x118 == 0);
	assert(c.x119 == 0);
	assert(c.x120 == 0);
	assert(c.x121 == 0);
	assert(c.x122 == 0);
	assert(c.x123 == 0);
	assert(c.x124 == 0);
	assert(c.x125 == 0);
	assert(c.x126 == 0);
	assert(c.x127 == 0);
	assert(c.x128 == 0);
	assert(c.x129 == 0);
	assert(c.x130 == 0);
	assert(c.x131 == 0);
	assert(c.x132 == 0);
	assert(c.x133 == 0);
	assert(c.x134 == 0);
	assert(c.x135 == 0);
	assert(c.x136 == 0);
	assert(c.x137 == 0);
	assert(c.x138 == 0);
	assert(c.x139 == 0);
	assert(c.x140 == 0);
	assert(c.x141 == 0);
	assert(c.x142 == 0);
	assert(c.x143 == 0);
	assert(c.x144 == 0);
	assert(c.x145 == 0);
	assert(c.x146 == 0);
	assert(c.x147 == 0);
	assert(c.x148 == 0);
	assert(c.x149 == 0);
	assert(c.x150 == 0);
	assert(c.x151 == 0);
	assert(c.x152 == 0);
	assert(c.x153 == 0);
	assert(c.x154 == 0);
	assert(c.x155 == 0);
	assert(c.x156 == 0);
	assert(c.x157 == 0);
	assert(c.x158 == 0);
	assert(c.x159 == 0);
	assert(c.x160 == 0);
	assert(c.x161 == 0);
	assert(c.x162 == 0);
	assert(c.x163 == 0);
	assert(c.x164 == 0);
	assert(c.x165 == 0);
	assert(c.x166 == 0);
	assert(c.x167 == 0);
	assert(c.x168 == 0);
	assert(c.x169 == 0);
	assert(c.x170 == 0);
	assert(c.x171 == 0);
	assert(c.x172 == 0);
	assert(c.x173 == 0);
	assert(c.x174 == 0);
	assert(c.x175 == 0);
	assert(c.x176 == 0);
	assert(c.x177 == 0);
	assert(c.x178 == 0);
	assert(c.x179 == 0);
	assert(c.x180 == 0);
	assert(c.x181 == 0);
	assert(c.x182 == 0);
	assert(c.x183 == 0);
	assert(c.x184 == 0);
	assert(c.x185 == 0);
	assert(c.x186 == 0);
	assert(c.x187 == 0);
	assert(c.x188 == 0);
	assert(c.x189 == 0);
	assert(c.x190 == 0);
	assert(c.x191 == 0);
	assert(c.x192 == 0);
	assert(c.x193 == 0);
	assert(c.x194 == 0);
	assert(c.x195 == 0);
	assert(c.x196 == 0);
	assert(c.x197 == 0);
	assert(c.x198 == 0);
	assert(c.x199 == 0);
	assert(c.x200 == 0);
	assert(c.x201 == 0);
	assert(c.x202 == 0);
	assert(c.x203 == 0);
	assert(c.x204 == 0);
	assert(c.x205 == 0);
	assert(c.x206 == 0);
	assert(c.x207 == 0);
	assert(c.x208 == 0);
	assert(c.x209 == 0);
	assert(c.x210 == 0);
	assert(c.x211 == 0);
	assert(c.x212 == 0);
	assert(c.x213 == 0);
	assert(c.x214 == 0);
	assert(c.x215 == 0);
	assert(c.x216 == 0);
	assert(c.x217 == 0);
	assert(c.x218 == 0);
	assert(c.x219 == 0);
	assert(c.x220 == 0);
	assert(c.x221 == 0);
	assert(c.x222 == 0);
	assert(c.x223 == 0);
	assert(c.x224 == 0);
	assert(c.x225 == 0);
	assert(c.x226 == 0);
	assert(c.x227 == 0);
	assert(c.x228 == 0);
	assert(c.x229 == 0);
	assert(c.x230 == 0);
	assert(c.x231 == 0);
	assert(c.x232 == 0);
	assert(c.x233 == 0);
	assert(c.x234 == 0);
	assert(c.x235 == 0);
	assert(c.x236 == 0);
	assert(c.x237 == 0);
	assert(c.x238 == 0);
	assert(c.x239 == 0);
	assert(c.x240 == 0);
	assert(c.x241 == 0);
	assert(c.x242 == 0);
	assert(c.x243 == 0);
	assert(c.x244 == 0);
	assert(c.x245 == 0);
	assert(c.x246 == 0);
	assert(c.x247 == 0);
	assert(c.x248 == 0);
	assert(c.x249 == 0);
	assert(c.x250 == 0);
	assert(c.x251 == 0);
	assert(c.x252 == 0);
	assert(c.x253 == 0);
	assert(c.x254 == 0);
	assert(c.x255 == 0);
	assert(c.x256 == 0);
	assert(c.x257 == 0);
	assert(c.x258 == 0);
	assert(c.x259 == 0);
	assert(c.x260 == 0);
	assert(c.x261 == 0);
	assert(c.x262 == 0);
	assert(c.x263 == 0);
	assert(c.x264 == 0);
	assert(c.x265 == 0);
	assert(c.x266 == 0);
	assert(c.x267 == 0);
	assert(c.x268 == 0);
	assert(c.x269 == 0);
	assert(c.x270 == 0);
	assert(c.x271 == 0);
	assert(c.x272 == 0);
	assert(c.x273 == 0);
	assert(c.x274 == 0);
	assert(c.x275 == 0);
	assert(c.x276 == 0);
	assert(c.x277 == 0);
	assert(c.x278 == 0);
	assert(c.x279 == 0);
	assert(c.x280 == 0);
	assert(c.x281 == 0);
	assert(c.x282 == 0);
	assert(c.x283 == 0);
	assert(c.x284 == 0);
	assert(c.x285 == 0);
	assert(c.x286 == 0);
	assert(c.x287 == 0);
	assert(c.x288 == 0);
	assert(c.x289 == 0);
	assert(c.x290 == 0);
	assert(c.x291 == 0);
	assert(c.x292 == 0);
	assert(c.x293 == 0);
	assert(c.x294 == 0);
	assert(c.x295 == 0);
	assert(c.x296 == 0);
	assert(c.x297 == 0);
	assert(c.x298 == 0);
	assert(c.x299 == 0);
	assert(c.x300 == 0);
	assert(c.x301 == 0);
	assert(c.x302 == 0);
	assert(c.x303 == 0);
	assert(c.x304 == 0);
	assert(c.x305 == 0);
	assert(c.x306 == 0);
	assert(c.x307 == 0);
	assert(c.x308 == 0);
	assert(c.x309 == 0);
	assert(c.x310 == 0);
	assert(c.x311 == 0);
	assert(c.x312 == 0);
	assert(c.x313 == 0);
	assert(c.x314 == 0);
	assert(c.x315 == 0);
	assert(c.x316 == 0);
	assert(c.x317 == 0);
	assert(c.x318 == 0);
	assert(c.x319 == 0);
	assert(c.x320 == 0);
	assert(c.x321 == 0);
	assert(c.x322 == 0);
	assert(c.x323 == 0);
	assert(c.x324 == 0);
	assert(c.x325 == 0);
	assert(c.x326 == 0);
	assert(c.x327 == 0);
	assert(c.x328 == 0);
	assert(c.x329 == 0);
	assert(c.x330 == 0);
	assert(c.x331 == 0);
	assert(c.x332 == 0);
	assert(c.x333 == 0);
	assert(c.x334 == 0);
	assert(c.x335 == 0);
	assert(c.x336 == 0);
	assert(c.x337 == 0);
	assert(c.x338 == 0);
	assert(c.x339 == 0);
	assert(c.x340 == 0);
	assert(c.x341 == 0);
	assert(c.x342 == 0);
	assert(c.x343 == 0);
	assert(c.x344 == 0);
	assert(c.x345 == 0);
	assert(c.x346 == 0);
	assert(c.x347 == 0);
	assert(c.x348 == 0);
	assert(c.x349 == 0);
	assert(c.x350 == 0);
	assert(c.x351 == 0);
	assert(c.x352 == 0);
	assert(c.x353 == 0);
	assert(c.x354 == 0);
	assert(c.x355 == 0);
	assert(c.x356 == 0);
	assert(c.x357 == 0);
	assert(c.x358 == 0);
	assert(c.x359 == 0);
	assert(c.x360 == 0);
	assert(c.x361 == 0);
	assert(c.x362 == 0);
	assert(c.x363 == 0);
	assert(c.x364 == 0);
	assert(c.x365 == 0);
	assert(c.x366 == 0);
	assert(c.x367 == 0);
	assert(c.x368 == 0);
	assert(c.x369 == 0);
	assert(c.x370 == 0);
	assert(c.x371 == 0);
	assert(c.x372 == 0);
	assert(c.x373 == 0);
	assert(c.x374 == 0);
	assert(c.x375 == 0);
	assert(c.x376 == 0);
	assert(c.x377 == 0);
	assert(c.x378 == 0);
	assert(c.x379 == 0);
	assert(c.x380 == 0);
	assert(c.x381 == 0);
	assert(c.x382 == 0);
	assert(c.x383 == 0);
	assert(c.x384 == 0);
	assert(c.x385 == 0);
	assert(c.x386 == 0);
	assert(c.x387 == 0);
	assert(c.x388 == 0);
	assert(c.x389 == 0);
	assert(c.x390 == 0);
	assert(c.x391 == 0);
	assert(c.x392 == 0);
	assert(c.x393 == 0);
	assert(c.x394 == 0);
	assert(c.x395 == 0);
	assert(c.x396 == 0);
	assert(c.x397 == 0);
	assert(c.x398 == 0);
	assert(c.x399 == 0);
	assert(c.x400 == 0);
	assert(c.x401 == 0);
	assert(c.x402 == 0);
	assert(c.x403 == 0);
	assert(c.x404 == 0);
	assert(c.x405 == 0);
	assert(c.x406 == 0);
	assert(c.x407 == 0);
	assert(c.x408 == 0);
	assert(c.x409 == 0);
	assert(c.x410 == 0);
	assert(c.x411 == 0);
	assert(c.x412 == 0);
	assert(c.x413 == 0);
	assert(c.x414 == 0);
	assert(c.x415 == 0);
	assert(c.x416 == 0);
	assert(c.x417 == 0);
	assert(c.x418 == 0);
	assert(c.x419 == 0);
	assert(c.x420 == 0);
	assert(c.x421 == 0);
	assert(c.x422 == 0);
	assert(c.x423 == 0);
	assert(c.x424 == 0);
	assert(c.x425 == 0);
	assert(c.x426 == 0);
	assert(c.x427 == 0);
	assert(c.x428 == 0);
	assert(c.x429 == 0);
	assert(c.x430 == 0);
	assert(c.x431 == 0);
	assert(c.x432 == 0);
	assert(c.x433 == 0);
	assert(c.x434 == 0);
	assert(c.x435 == 0);
	assert(c.x436 == 0);
	assert(c.x437 == 0);
	assert(c.x438 == 0);
	assert(c.x439 == 0);
	assert(c.x440 == 0);
	assert(c.x441 == 0);
	assert(c.x442 == 0);
	assert(c.x443 == 0);
	assert(c.x444 == 0);
	assert(c.x445 == 0);
	assert(c.x446 == 0);
	assert(c.x447 == 0);
	assert(c.x448 == 0);
	assert(c.x449 == 0);
	assert(c.x450 == 0);
	assert(c.x451 == 0);
	assert(c.x452 == 0);
	assert(c.x453 == 0);
	assert(c.x454 == 0);
	assert(c.x455 == 0);
	assert(c.x456 == 0);
	assert(c.x457 == 0);
	assert(c.x458 == 0);
	assert(c.x459 == 0);
	assert(c.x460 == 0);
	assert(c.x461 == 0);
	assert(c.x462 == 0);
	assert(c.x463 == 0);
	assert(c.x464 == 0);
	assert(c.x465 == 0);
	assert(c.x466 == 0);
	assert(c.x467 == 0);
	assert(c.x468 == 0);
	assert(c.x469 == 0);
	assert(c.x470 == 0);
	assert(c.x471 == 0);
	assert(c.x472 == 0);
	assert(c.x473 == 0);
	assert(c.x474 == 0);
	assert(c.x475 == 0);
	assert(c.x476 == 0);
	assert(c.x477 == 0);
	assert(c.x478 == 0);
	assert(c.x479 == 0);
	assert(c.x480 == 0);
	assert(c.x481 == 0);
	assert(c.x482 == 0);
	assert(c.x483 == 0);
	assert(c.x484 == 0);
	assert(c.x485 == 0);
	assert(c.x486 == 0);
	assert(c.x487 == 0);
	assert(c.x488 == 0);
	assert(c.x489 == 0);
	assert(c.x490 == 0);
	assert(c.x491 == 0);
	assert(c.x492 == 0);
	assert(c.x493 == 0);
	assert(c.x494 == 0);
	assert(c.x495 == 0);
	assert(c.x496 == 0);
	assert(c.x497 == 0);
	assert(c.x498 == 0);
	assert(c.x499 == 0);

}

test();
